export interface DrugSpec {
  /** ASCII-safe slug from SKU, e.g. "kha-001" */
  id: string;
  /** Original SKU from danh mục, e.g. "KHÁ-001" */
  sku: string;
  /** Tên thuốc/sản phẩm theo danh mục */
  name: string;
  /** Tên thương mại hiển thị trên hộp (mặc định = name) */
  brand: string;
  /** Tên hoạt chất / generic (mặc định = name) */
  generic: string;
  /** Hàm lượng, vd "500 mg" */
  strength: string;
  /** Dạng bào chế: Viên nén, Viên nang, Siro, Gói, … */
  form: string;
  /** Phân nhóm theo Excel (13 nhóm) */
  category: string;
  /** ID tủ chứa thuốc — xem CABINETS bên dưới */
  cabinetId: string;
  /** Quy cách đóng gói (vd "Hộp 10 vỉ x 10 viên") */
  pack: string;
  /** Đơn vị lấy nhỏ nhất khi ra lẻ */
  retailUnit: string;
  /** Mã vạch mô phỏng */
  barcode: string;
  /** Nhà sản xuất (chưa cập nhật → "—") */
  manufacturer: string;
  /** Số đăng ký — tạm dùng SKU */
  sdk: string;
  isRx: boolean;
  isAntibiotic?: boolean;
  isHazardPregnancy?: boolean;
  /** alias của cabinetId — giữ cho code cũ */
  groupId: string;
  /** Nhãn nhóm hiển thị trên cabinet/POS */
  groupLabel: string;
  /** Màu nhấn của nhóm (border/poster) */
  groupAccent: string;
  /** Màu nền hộp thuốc */
  bodyColor: string;
  textDark?: boolean;
  /** Số hộp xếp cạnh nhau trên kệ (mặc định 3) */
  boxesPerRow: number;
  /** Giá bán lẻ (VND/hộp) — placeholder theo dạng bào chế */
  unitPrice: number;
}

/** 7 tủ lớn + 1 tủ quầy ngang (3 ngăn) theo Yêu cầu 2.docx */
export interface CabinetSpec {
  id: string;
  label: string;
  accent: string;
  zone: "back" | "side" | "front";
  /** Vị trí trên kệ ngang trong khu vực (0,1,2,3 với "back"; 0,1,2 với "side"/"front") */
  slot: number;
  /** Tủ kê đơn? */
  isRx: boolean;
}

export const CABINETS: CabinetSpec[] = [
  // Phía sau lưng dược sĩ: 4 tủ lớn (2 Rx + 2 OTC)
  { id: "rx_abx",          label: "KHÁNG SINH (KÊ ĐƠN)",            accent: "#dc2626", zone: "back",  slot: 0, isRx: true  },
  { id: "rx_cardio_dm",    label: "TIM MẠCH – TIỂU ĐƯỜNG (KÊ ĐƠN)", accent: "#ea580c", zone: "back",  slot: 1, isRx: true  },
  { id: "otc_pain_cold",   label: "GIẢM ĐAU – HẠ SỐT – HO CẢM",     accent: "#2563eb", zone: "back",  slot: 2, isRx: false },
  { id: "otc_resp_gi",     label: "HÔ HẤP – TIÊU HOÁ",              accent: "#0d9488", zone: "back",  slot: 3, isRx: false },
  // Phía bên tay phải dược sĩ: 3 tủ (dược liệu/TPCN/mỹ phẩm)
  { id: "side_herbal",     label: "DƯỢC LIỆU – Y HỌC CỔ TRUYỀN",    accent: "#92400e", zone: "side",  slot: 0, isRx: false },
  { id: "side_supp",       label: "TPCN – VITAMIN – KHOÁNG CHẤT",   accent: "#ca8a04", zone: "side",  slot: 1, isRx: false },
  { id: "side_cosmetic",   label: "MỸ PHẨM – DỤNG CỤ Y TẾ",         accent: "#db2777", zone: "side",  slot: 2, isRx: false },
  // Quầy ngang phía trước: 3 ngăn (nhỏ mắt/nhỏ mũi/dùng ngoài)
  { id: "front_eye",       label: "NHỎ MẮT",                        accent: "#14b8a6", zone: "front", slot: 0, isRx: false },
  { id: "front_nose",      label: "NHỎ MŨI",                        accent: "#0ea5e9", zone: "front", slot: 1, isRx: false },
  { id: "front_topical",   label: "DÙNG NGOÀI",                     accent: "#7c3aed", zone: "front", slot: 2, isRx: false }
];

export function getCabinet(id: string): CabinetSpec | undefined {
  return CABINETS.find((c) => c.id === id);
}

// ALL_DRUGS ------------------------------
export const ALL_DRUGS: DrugSpec[] = [
  { id: "kha-001", sku: "KHÁ-001", name: "Amoxicillin", brand: "Amoxicillin", generic: "Amoxicillin", strength: "500 mg", form: "Viên nang", category: "Kháng sinh", cabinetId: "rx_abx", pack: "Hộp 10 vỉ x 10 viên", retailUnit: "1 vỉ / 1 viên", barcode: "8933413730974", manufacturer: "—", sdk: "KHÁ-001", isRx: true, isAntibiotic: true, groupId: "rx_abx", groupLabel: "KHÁNG SINH (KÊ ĐƠN)", groupAccent: "#dc2626", bodyColor: "#fef2f2", textDark: true, boxesPerRow: 3, unitPrice: 30000 },
  { id: "kha-002", sku: "KHÁ-002", name: "Cefixim", brand: "Cefixim", generic: "Cefixim", strength: "200 mg", form: "Viên nang", category: "Kháng sinh", cabinetId: "rx_abx", pack: "Hộp 10 vỉ x 10 viên", retailUnit: "1 vỉ / 1 viên", barcode: "8931749939437", manufacturer: "—", sdk: "KHÁ-002", isRx: true, isAntibiotic: true, groupId: "rx_abx", groupLabel: "KHÁNG SINH (KÊ ĐƠN)", groupAccent: "#dc2626", bodyColor: "#fef2f2", textDark: true, boxesPerRow: 3, unitPrice: 30000 },
  { id: "kha-003", sku: "KHÁ-003", name: "Azithromycin", brand: "Azithromycin", generic: "Azithromycin", strength: "500 mg", form: "Viên nén", category: "Kháng sinh", cabinetId: "rx_abx", pack: "Hộp 10 vỉ x 10 viên", retailUnit: "1 vỉ / 1 viên", barcode: "8939453830013", manufacturer: "—", sdk: "KHÁ-003", isRx: true, isAntibiotic: true, groupId: "rx_abx", groupLabel: "KHÁNG SINH (KÊ ĐƠN)", groupAccent: "#dc2626", bodyColor: "#fef2f2", textDark: true, boxesPerRow: 3, unitPrice: 18000 },
  { id: "kha-004", sku: "KHÁ-004", name: "Cefuroxim", brand: "Cefuroxim", generic: "Cefuroxim", strength: "500 mg", form: "Viên nén", category: "Kháng sinh", cabinetId: "rx_abx", pack: "Hộp 10 vỉ x 10 viên", retailUnit: "1 vỉ / 1 viên", barcode: "8932945200412", manufacturer: "—", sdk: "KHÁ-004", isRx: true, isAntibiotic: true, groupId: "rx_abx", groupLabel: "KHÁNG SINH (KÊ ĐƠN)", groupAccent: "#dc2626", bodyColor: "#fef2f2", textDark: true, boxesPerRow: 3, unitPrice: 18000 },
  { id: "kha-005", sku: "KHÁ-005", name: "Levofloxacin", brand: "Levofloxacin", generic: "Levofloxacin", strength: "500 mg", form: "Viên nén", category: "Kháng sinh", cabinetId: "rx_abx", pack: "Hộp 10 vỉ x 10 viên", retailUnit: "1 vỉ / 1 viên", barcode: "8939694996477", manufacturer: "—", sdk: "KHÁ-005", isRx: true, isAntibiotic: true, groupId: "rx_abx", groupLabel: "KHÁNG SINH (KÊ ĐƠN)", groupAccent: "#dc2626", bodyColor: "#fef2f2", textDark: true, boxesPerRow: 3, unitPrice: 18000 },
  { id: "kha-006", sku: "KHÁ-006", name: "Doxycyclin", brand: "Doxycyclin", generic: "Doxycyclin", strength: "100 mg", form: "Viên nang", category: "Kháng sinh", cabinetId: "rx_abx", pack: "Hộp 10 vỉ x 10 viên", retailUnit: "1 vỉ / 1 viên", barcode: "8935122790514", manufacturer: "—", sdk: "KHÁ-006", isRx: true, isAntibiotic: true, isHazardPregnancy: true, groupId: "rx_abx", groupLabel: "KHÁNG SINH (KÊ ĐƠN)", groupAccent: "#dc2626", bodyColor: "#fef2f2", textDark: true, boxesPerRow: 3, unitPrice: 30000 },
  { id: "kha-007", sku: "KHÁ-007", name: "Metronidazol", brand: "Metronidazol", generic: "Metronidazol", strength: "250 mg", form: "Viên nén", category: "Kháng sinh", cabinetId: "rx_abx", pack: "Hộp 10 vỉ x 10 viên", retailUnit: "1 vỉ / 1 viên", barcode: "8938672301098", manufacturer: "—", sdk: "KHÁ-007", isRx: true, isAntibiotic: true, groupId: "rx_abx", groupLabel: "KHÁNG SINH (KÊ ĐƠN)", groupAccent: "#dc2626", bodyColor: "#fef2f2", textDark: true, boxesPerRow: 3, unitPrice: 18000 },
  { id: "kha-008", sku: "KHÁ-008", name: "Clarithromycin", brand: "Clarithromycin", generic: "Clarithromycin", strength: "500 mg", form: "Viên nén", category: "Kháng sinh", cabinetId: "rx_abx", pack: "Hộp 10 vỉ x 10 viên", retailUnit: "1 vỉ / 1 viên", barcode: "8931384794627", manufacturer: "—", sdk: "KHÁ-008", isRx: true, isAntibiotic: true, groupId: "rx_abx", groupLabel: "KHÁNG SINH (KÊ ĐƠN)", groupAccent: "#dc2626", bodyColor: "#fef2f2", textDark: true, boxesPerRow: 3, unitPrice: 18000 },
  { id: "kha-009", sku: "KHÁ-009", name: "Ciprofloxacin", brand: "Ciprofloxacin", generic: "Ciprofloxacin", strength: "500 mg", form: "Viên nén", category: "Kháng sinh", cabinetId: "rx_abx", pack: "Hộp 10 vỉ x 10 viên", retailUnit: "1 vỉ / 1 viên", barcode: "8938498798733", manufacturer: "—", sdk: "KHÁ-009", isRx: true, isAntibiotic: true, groupId: "rx_abx", groupLabel: "KHÁNG SINH (KÊ ĐƠN)", groupAccent: "#dc2626", bodyColor: "#fef2f2", textDark: true, boxesPerRow: 3, unitPrice: 18000 },
  { id: "kha-010", sku: "KHÁ-010", name: "Cefpodoxim", brand: "Cefpodoxim", generic: "Cefpodoxim", strength: "200 mg", form: "Viên nén", category: "Kháng sinh", cabinetId: "rx_abx", pack: "Hộp 10 vỉ x 10 viên", retailUnit: "1 vỉ / 1 viên", barcode: "8934581229012", manufacturer: "—", sdk: "KHÁ-010", isRx: true, isAntibiotic: true, groupId: "rx_abx", groupLabel: "KHÁNG SINH (KÊ ĐƠN)", groupAccent: "#dc2626", bodyColor: "#fef2f2", textDark: true, boxesPerRow: 3, unitPrice: 18000 },
  { id: "kha-011", sku: "KHÁ-011", name: "Ampicillin", brand: "Ampicillin", generic: "Ampicillin", strength: "500 mg", form: "Viên nang", category: "Kháng sinh", cabinetId: "rx_abx", pack: "Hộp 10 vỉ x 10 viên", retailUnit: "1 vỉ / 1 viên", barcode: "8938458638063", manufacturer: "—", sdk: "KHÁ-011", isRx: true, isAntibiotic: true, groupId: "rx_abx", groupLabel: "KHÁNG SINH (KÊ ĐƠN)", groupAccent: "#dc2626", bodyColor: "#fef2f2", textDark: true, boxesPerRow: 3, unitPrice: 30000 },
  { id: "kha-012", sku: "KHÁ-012", name: "Roxithromycin", brand: "Roxithromycin", generic: "Roxithromycin", strength: "150 mg", form: "Viên nén", category: "Kháng sinh", cabinetId: "rx_abx", pack: "Hộp 10 vỉ x 10 viên", retailUnit: "1 vỉ / 1 viên", barcode: "8939641317615", manufacturer: "—", sdk: "KHÁ-012", isRx: true, isAntibiotic: true, groupId: "rx_abx", groupLabel: "KHÁNG SINH (KÊ ĐƠN)", groupAccent: "#dc2626", bodyColor: "#fef2f2", textDark: true, boxesPerRow: 3, unitPrice: 18000 },
  { id: "kha-013", sku: "KHÁ-013", name: "Erythromycin", brand: "Erythromycin", generic: "Erythromycin", strength: "500 mg", form: "Viên nén", category: "Kháng sinh", cabinetId: "rx_abx", pack: "Hộp 10 vỉ x 10 viên", retailUnit: "1 vỉ / 1 viên", barcode: "8934781393794", manufacturer: "—", sdk: "KHÁ-013", isRx: true, isAntibiotic: true, groupId: "rx_abx", groupLabel: "KHÁNG SINH (KÊ ĐƠN)", groupAccent: "#dc2626", bodyColor: "#fef2f2", textDark: true, boxesPerRow: 3, unitPrice: 18000 },
  { id: "kha-014", sku: "KHÁ-014", name: "Cefalexin", brand: "Cefalexin", generic: "Cefalexin", strength: "500 mg", form: "Viên nang", category: "Kháng sinh", cabinetId: "rx_abx", pack: "Hộp 10 vỉ x 10 viên", retailUnit: "1 vỉ / 1 viên", barcode: "8939677266644", manufacturer: "—", sdk: "KHÁ-014", isRx: true, isAntibiotic: true, groupId: "rx_abx", groupLabel: "KHÁNG SINH (KÊ ĐƠN)", groupAccent: "#dc2626", bodyColor: "#fef2f2", textDark: true, boxesPerRow: 3, unitPrice: 30000 },
  { id: "kha-015", sku: "KHÁ-015", name: "Moxifloxacin", brand: "Moxifloxacin", generic: "Moxifloxacin", strength: "400 mg", form: "Viên nén", category: "Kháng sinh", cabinetId: "rx_abx", pack: "Hộp 10 vỉ x 10 viên", retailUnit: "1 vỉ / 1 viên", barcode: "8936519474653", manufacturer: "—", sdk: "KHÁ-015", isRx: true, isAntibiotic: true, groupId: "rx_abx", groupLabel: "KHÁNG SINH (KÊ ĐƠN)", groupAccent: "#dc2626", bodyColor: "#fef2f2", textDark: true, boxesPerRow: 3, unitPrice: 18000 },
  { id: "ho-016", sku: "HÔ -016", name: "Acetylcystein", brand: "Acetylcystein", generic: "Acetylcystein", strength: "200 mg", form: "Gói", category: "Hô hấp", cabinetId: "otc_resp_gi", pack: "1 chai/hộp", retailUnit: "1 đơn vị", barcode: "8932943821571", manufacturer: "—", sdk: "HÔ -016", isRx: false, groupId: "otc_resp_gi", groupLabel: "HÔ HẤP – TIÊU HOÁ", groupAccent: "#0d9488", bodyColor: "#ecfdf5", textDark: true, boxesPerRow: 3, unitPrice: 25000 },
  { id: "ho-017", sku: "HÔ -017", name: "Bromhexin", brand: "Bromhexin", generic: "Bromhexin", strength: "8 mg", form: "Viên nén", category: "Hô hấp", cabinetId: "otc_resp_gi", pack: "Hộp 10 vỉ x 10 viên", retailUnit: "1 vỉ / 1 viên", barcode: "8932005330200", manufacturer: "—", sdk: "HÔ -017", isRx: false, groupId: "otc_resp_gi", groupLabel: "HÔ HẤP – TIÊU HOÁ", groupAccent: "#0d9488", bodyColor: "#ecfdf5", textDark: true, boxesPerRow: 3, unitPrice: 18000 },
  { id: "ho-018", sku: "HÔ -018", name: "Salbutamol", brand: "Salbutamol", generic: "Salbutamol", strength: "2 mg", form: "Viên nén", category: "Hô hấp", cabinetId: "otc_resp_gi", pack: "Hộp 10 vỉ x 10 viên", retailUnit: "1 vỉ / 1 viên", barcode: "8939241408256", manufacturer: "—", sdk: "HÔ -018", isRx: false, groupId: "otc_resp_gi", groupLabel: "HÔ HẤP – TIÊU HOÁ", groupAccent: "#0d9488", bodyColor: "#ecfdf5", textDark: true, boxesPerRow: 3, unitPrice: 18000 },
  { id: "ho-019", sku: "HÔ -019", name: "Ventolin", brand: "Ventolin", generic: "Ventolin", strength: "100 mcg", form: "Bình xịt", category: "Hô hấp", cabinetId: "otc_resp_gi", pack: "1 chai/hộp", retailUnit: "1 đơn vị", barcode: "8934650462030", manufacturer: "—", sdk: "HÔ -019", isRx: false, groupId: "otc_resp_gi", groupLabel: "HÔ HẤP – TIÊU HOÁ", groupAccent: "#0d9488", bodyColor: "#ecfdf5", textDark: true, boxesPerRow: 3, unitPrice: 95000 },
  { id: "ho-020", sku: "HÔ -020", name: "Seretide", brand: "Seretide", generic: "Seretide", strength: "250 mcg", form: "Bình xịt", category: "Hô hấp", cabinetId: "otc_resp_gi", pack: "1 chai/hộp", retailUnit: "1 đơn vị", barcode: "8932063597450", manufacturer: "—", sdk: "HÔ -020", isRx: false, groupId: "otc_resp_gi", groupLabel: "HÔ HẤP – TIÊU HOÁ", groupAccent: "#0d9488", bodyColor: "#ecfdf5", textDark: true, boxesPerRow: 3, unitPrice: 95000 },
  { id: "ho-021", sku: "HÔ -021", name: "Montelukast", brand: "Montelukast", generic: "Montelukast", strength: "10 mg", form: "Viên nén", category: "Hô hấp", cabinetId: "otc_resp_gi", pack: "Hộp 10 vỉ x 10 viên", retailUnit: "1 vỉ / 1 viên", barcode: "8935990286339", manufacturer: "—", sdk: "HÔ -021", isRx: false, groupId: "otc_resp_gi", groupLabel: "HÔ HẤP – TIÊU HOÁ", groupAccent: "#0d9488", bodyColor: "#ecfdf5", textDark: true, boxesPerRow: 3, unitPrice: 18000 },
  { id: "ho-022", sku: "HÔ -022", name: "Theophyllin", brand: "Theophyllin", generic: "Theophyllin", strength: "100 mg", form: "Viên nén", category: "Hô hấp", cabinetId: "otc_resp_gi", pack: "Hộp 10 vỉ x 10 viên", retailUnit: "1 vỉ / 1 viên", barcode: "8935224124155", manufacturer: "—", sdk: "HÔ -022", isRx: false, groupId: "otc_resp_gi", groupLabel: "HÔ HẤP – TIÊU HOÁ", groupAccent: "#0d9488", bodyColor: "#ecfdf5", textDark: true, boxesPerRow: 3, unitPrice: 18000 },
  { id: "ho-023", sku: "HÔ -023", name: "Prospan", brand: "Prospan", generic: "Prospan", strength: "100 ml", form: "Siro", category: "Hô hấp", cabinetId: "otc_resp_gi", pack: "1 chai/hộp", retailUnit: "1 đơn vị", barcode: "8933272756571", manufacturer: "—", sdk: "HÔ -023", isRx: false, groupId: "otc_resp_gi", groupLabel: "HÔ HẤP – TIÊU HOÁ", groupAccent: "#0d9488", bodyColor: "#ecfdf5", textDark: true, boxesPerRow: 3, unitPrice: 45000 },
  { id: "ho-024", sku: "HÔ -024", name: "Pulmicort", brand: "Pulmicort", generic: "Pulmicort", strength: "0.5 mg", form: "Ống khí dung", category: "Hô hấp", cabinetId: "otc_resp_gi", pack: "1 chai/hộp", retailUnit: "1 đơn vị", barcode: "8936966955911", manufacturer: "—", sdk: "HÔ -024", isRx: false, groupId: "otc_resp_gi", groupLabel: "HÔ HẤP – TIÊU HOÁ", groupAccent: "#0d9488", bodyColor: "#ecfdf5", textDark: true, boxesPerRow: 3, unitPrice: 85000 },
  { id: "ho-025", sku: "HÔ -025", name: "Terbutalin", brand: "Terbutalin", generic: "Terbutalin", strength: "5 mg", form: "Viên nén", category: "Hô hấp", cabinetId: "otc_resp_gi", pack: "Hộp 10 vỉ x 10 viên", retailUnit: "1 vỉ / 1 viên", barcode: "8932586525402", manufacturer: "—", sdk: "HÔ -025", isRx: false, groupId: "otc_resp_gi", groupLabel: "HÔ HẤP – TIÊU HOÁ", groupAccent: "#0d9488", bodyColor: "#ecfdf5", textDark: true, boxesPerRow: 3, unitPrice: 18000 },
  { id: "ho-026", sku: "HÔ -026", name: "Ambroxol", brand: "Ambroxol", generic: "Ambroxol", strength: "30 mg", form: "Viên nén", category: "Hô hấp", cabinetId: "otc_resp_gi", pack: "Hộp 10 vỉ x 10 viên", retailUnit: "1 vỉ / 1 viên", barcode: "8938077580337", manufacturer: "—", sdk: "HÔ -026", isRx: false, groupId: "otc_resp_gi", groupLabel: "HÔ HẤP – TIÊU HOÁ", groupAccent: "#0d9488", bodyColor: "#ecfdf5", textDark: true, boxesPerRow: 3, unitPrice: 18000 },
  { id: "ho-027", sku: "HÔ -027", name: "Eucalyptol", brand: "Eucalyptol", generic: "Eucalyptol", strength: " ", form: "Viên nang", category: "Hô hấp", cabinetId: "otc_resp_gi", pack: "Hộp 10 vỉ x 10 viên", retailUnit: "1 vỉ / 1 viên", barcode: "8933475216891", manufacturer: "—", sdk: "HÔ -027", isRx: false, groupId: "otc_resp_gi", groupLabel: "HÔ HẤP – TIÊU HOÁ", groupAccent: "#0d9488", bodyColor: "#ecfdf5", textDark: true, boxesPerRow: 3, unitPrice: 30000 },
  { id: "ho-028", sku: "HO -028", name: "Tiffy", brand: "Tiffy", generic: "Tiffy", strength: " ", form: "Viên nang", category: "Ho cảm", cabinetId: "otc_pain_cold", pack: "Hộp 10 vỉ x 10 viên", retailUnit: "1 vỉ / 1 viên", barcode: "8933205963993", manufacturer: "—", sdk: "HO -028", isRx: false, groupId: "otc_pain_cold", groupLabel: "GIẢM ĐAU – HẠ SỐT – HO CẢM", groupAccent: "#2563eb", bodyColor: "#eff6ff", textDark: true, boxesPerRow: 3, unitPrice: 30000 },
  { id: "ho-029", sku: "HO -029", name: "Hapacol cảm cúm", brand: "Hapacol cảm cúm", generic: "Hapacol cảm cúm", strength: " ", form: "Viên nang", category: "Ho cảm", cabinetId: "otc_pain_cold", pack: "Hộp 10 vỉ x 10 viên", retailUnit: "1 vỉ / 1 viên", barcode: "8938891131405", manufacturer: "—", sdk: "HO -029", isRx: false, groupId: "otc_pain_cold", groupLabel: "GIẢM ĐAU – HẠ SỐT – HO CẢM", groupAccent: "#2563eb", bodyColor: "#eff6ff", textDark: true, boxesPerRow: 3, unitPrice: 30000 },
  { id: "ho-030", sku: "HO -030", name: "Decolgen", brand: "Decolgen", generic: "Decolgen", strength: " ", form: "Viên nén", category: "Ho cảm", cabinetId: "otc_pain_cold", pack: "Hộp 10 vỉ x 10 viên", retailUnit: "1 vỉ / 1 viên", barcode: "8937317954042", manufacturer: "—", sdk: "HO -030", isRx: false, groupId: "otc_pain_cold", groupLabel: "GIẢM ĐAU – HẠ SỐT – HO CẢM", groupAccent: "#2563eb", bodyColor: "#eff6ff", textDark: true, boxesPerRow: 3, unitPrice: 18000 },
  { id: "ho-031", sku: "HO -031", name: "Dextromethorphan", brand: "Dextromethorphan", generic: "Dextromethorphan", strength: "15 mg", form: "Viên nang", category: "Ho cảm", cabinetId: "otc_pain_cold", pack: "Hộp 10 vỉ x 10 viên", retailUnit: "1 vỉ / 1 viên", barcode: "8936106060804", manufacturer: "—", sdk: "HO -031", isRx: false, groupId: "otc_pain_cold", groupLabel: "GIẢM ĐAU – HẠ SỐT – HO CẢM", groupAccent: "#2563eb", bodyColor: "#eff6ff", textDark: true, boxesPerRow: 3, unitPrice: 30000 },
  { id: "ho-032", sku: "HO -032", name: "Terpin codein", brand: "Terpin codein", generic: "Terpin codein", strength: " ", form: "Viên nén", category: "Ho cảm", cabinetId: "otc_pain_cold", pack: "Hộp 10 vỉ x 10 viên", retailUnit: "1 vỉ / 1 viên", barcode: "8933450035305", manufacturer: "—", sdk: "HO -032", isRx: false, groupId: "otc_pain_cold", groupLabel: "GIẢM ĐAU – HẠ SỐT – HO CẢM", groupAccent: "#2563eb", bodyColor: "#eff6ff", textDark: true, boxesPerRow: 3, unitPrice: 18000 },
  { id: "ho-033", sku: "HO -033", name: "Cetirizin", brand: "Cetirizin", generic: "Cetirizin", strength: "10 mg", form: "Viên nén", category: "Ho cảm", cabinetId: "otc_pain_cold", pack: "Hộp 10 vỉ x 10 viên", retailUnit: "1 vỉ / 1 viên", barcode: "8932841386391", manufacturer: "—", sdk: "HO -033", isRx: false, groupId: "otc_pain_cold", groupLabel: "GIẢM ĐAU – HẠ SỐT – HO CẢM", groupAccent: "#2563eb", bodyColor: "#eff6ff", textDark: true, boxesPerRow: 3, unitPrice: 18000 },
  { id: "ho-034", sku: "HO -034", name: "Loratadin", brand: "Loratadin", generic: "Loratadin", strength: "10 mg", form: "Viên nén", category: "Ho cảm", cabinetId: "otc_pain_cold", pack: "Hộp 10 vỉ x 10 viên", retailUnit: "1 vỉ / 1 viên", barcode: "8935147219607", manufacturer: "—", sdk: "HO -034", isRx: false, groupId: "otc_pain_cold", groupLabel: "GIẢM ĐAU – HẠ SỐT – HO CẢM", groupAccent: "#2563eb", bodyColor: "#eff6ff", textDark: true, boxesPerRow: 3, unitPrice: 18000 },
  { id: "ho-035", sku: "HO -035", name: "Fexofenadin", brand: "Fexofenadin", generic: "Fexofenadin", strength: "180 mg", form: "Viên nén", category: "Ho cảm", cabinetId: "otc_pain_cold", pack: "Hộp 10 vỉ x 10 viên", retailUnit: "1 vỉ / 1 viên", barcode: "8936813153865", manufacturer: "—", sdk: "HO -035", isRx: false, groupId: "otc_pain_cold", groupLabel: "GIẢM ĐAU – HẠ SỐT – HO CẢM", groupAccent: "#2563eb", bodyColor: "#eff6ff", textDark: true, boxesPerRow: 3, unitPrice: 18000 },
  { id: "ho-036", sku: "HO -036", name: "Xịt họng Tantum", brand: "Xịt họng Tantum", generic: "Xịt họng Tantum", strength: "30 ml", form: "Dung dịch xịt", category: "Ho cảm", cabinetId: "otc_pain_cold", pack: "1 chai/hộp", retailUnit: "1 đơn vị", barcode: "8934108153411", manufacturer: "—", sdk: "HO -036", isRx: false, groupId: "otc_pain_cold", groupLabel: "GIẢM ĐAU – HẠ SỐT – HO CẢM", groupAccent: "#2563eb", bodyColor: "#eff6ff", textDark: true, boxesPerRow: 3, unitPrice: 65000 },
  { id: "ho-037", sku: "HO -037", name: "Strepsils", brand: "Strepsils", generic: "Strepsils", strength: " ", form: "Viên ngậm", category: "Ho cảm", cabinetId: "otc_pain_cold", pack: "Hộp 10 vỉ x 10 viên", retailUnit: "1 vỉ / 1 viên", barcode: "8936239118197", manufacturer: "—", sdk: "HO -037", isRx: false, groupId: "otc_pain_cold", groupLabel: "GIẢM ĐAU – HẠ SỐT – HO CẢM", groupAccent: "#2563eb", bodyColor: "#eff6ff", textDark: true, boxesPerRow: 3, unitPrice: 28000 },
  { id: "ho-038", sku: "HO -038", name: "Eugica", brand: "Eugica", generic: "Eugica", strength: " ", form: "Viên nang", category: "Ho cảm", cabinetId: "otc_pain_cold", pack: "Hộp 10 vỉ x 10 viên", retailUnit: "1 vỉ / 1 viên", barcode: "8937840664421", manufacturer: "—", sdk: "HO -038", isRx: false, groupId: "otc_pain_cold", groupLabel: "GIẢM ĐAU – HẠ SỐT – HO CẢM", groupAccent: "#2563eb", bodyColor: "#eff6ff", textDark: true, boxesPerRow: 3, unitPrice: 30000 },
  { id: "ho-039", sku: "HO -039", name: "Rhumenol", brand: "Rhumenol", generic: "Rhumenol", strength: " ", form: "Viên nang", category: "Ho cảm", cabinetId: "otc_pain_cold", pack: "Hộp 10 vỉ x 10 viên", retailUnit: "1 vỉ / 1 viên", barcode: "8936680792812", manufacturer: "—", sdk: "HO -039", isRx: false, groupId: "otc_pain_cold", groupLabel: "GIẢM ĐAU – HẠ SỐT – HO CẢM", groupAccent: "#2563eb", bodyColor: "#eff6ff", textDark: true, boxesPerRow: 3, unitPrice: 30000 },
  { id: "tim-040", sku: "TIM-040", name: "Amlodipin", brand: "Amlodipin", generic: "Amlodipin", strength: "5 mg", form: "Viên nén", category: "Tim mạch", cabinetId: "rx_cardio_dm", pack: "Hộp 10 vỉ x 10 viên", retailUnit: "1 vỉ / 1 viên", barcode: "8939562407907", manufacturer: "—", sdk: "TIM-040", isRx: true, groupId: "rx_cardio_dm", groupLabel: "TIM MẠCH – TIỂU ĐƯỜNG (KÊ ĐƠN)", groupAccent: "#ea580c", bodyColor: "#fff7ed", textDark: true, boxesPerRow: 3, unitPrice: 18000 },
  { id: "tim-041", sku: "TIM-041", name: "Bisoprolol", brand: "Bisoprolol", generic: "Bisoprolol", strength: "5 mg", form: "Viên nén", category: "Tim mạch", cabinetId: "rx_cardio_dm", pack: "Hộp 10 vỉ x 10 viên", retailUnit: "1 vỉ / 1 viên", barcode: "8934026131874", manufacturer: "—", sdk: "TIM-041", isRx: true, groupId: "rx_cardio_dm", groupLabel: "TIM MẠCH – TIỂU ĐƯỜNG (KÊ ĐƠN)", groupAccent: "#ea580c", bodyColor: "#fff7ed", textDark: true, boxesPerRow: 3, unitPrice: 18000 },
  { id: "tim-042", sku: "TIM-042", name: "Perindopril", brand: "Perindopril", generic: "Perindopril", strength: "5 mg", form: "Viên nén", category: "Tim mạch", cabinetId: "rx_cardio_dm", pack: "Hộp 10 vỉ x 10 viên", retailUnit: "1 vỉ / 1 viên", barcode: "8931313020438", manufacturer: "—", sdk: "TIM-042", isRx: true, groupId: "rx_cardio_dm", groupLabel: "TIM MẠCH – TIỂU ĐƯỜNG (KÊ ĐƠN)", groupAccent: "#ea580c", bodyColor: "#fff7ed", textDark: true, boxesPerRow: 3, unitPrice: 18000 },
  { id: "tim-043", sku: "TIM-043", name: "Losartan", brand: "Losartan", generic: "Losartan", strength: "50 mg", form: "Viên nén", category: "Tim mạch", cabinetId: "rx_cardio_dm", pack: "Hộp 10 vỉ x 10 viên", retailUnit: "1 vỉ / 1 viên", barcode: "8937564388607", manufacturer: "—", sdk: "TIM-043", isRx: true, groupId: "rx_cardio_dm", groupLabel: "TIM MẠCH – TIỂU ĐƯỜNG (KÊ ĐƠN)", groupAccent: "#ea580c", bodyColor: "#fff7ed", textDark: true, boxesPerRow: 3, unitPrice: 18000 },
  { id: "tim-044", sku: "TIM-044", name: "Valsartan", brand: "Valsartan", generic: "Valsartan", strength: "80 mg", form: "Viên nén", category: "Tim mạch", cabinetId: "rx_cardio_dm", pack: "Hộp 10 vỉ x 10 viên", retailUnit: "1 vỉ / 1 viên", barcode: "8937107570517", manufacturer: "—", sdk: "TIM-044", isRx: true, groupId: "rx_cardio_dm", groupLabel: "TIM MẠCH – TIỂU ĐƯỜNG (KÊ ĐƠN)", groupAccent: "#ea580c", bodyColor: "#fff7ed", textDark: true, boxesPerRow: 3, unitPrice: 18000 },
  { id: "tim-045", sku: "TIM-045", name: "Nifedipin", brand: "Nifedipin", generic: "Nifedipin", strength: "20 mg", form: "Viên nang", category: "Tim mạch", cabinetId: "rx_cardio_dm", pack: "Hộp 10 vỉ x 10 viên", retailUnit: "1 vỉ / 1 viên", barcode: "8931755775651", manufacturer: "—", sdk: "TIM-045", isRx: true, groupId: "rx_cardio_dm", groupLabel: "TIM MẠCH – TIỂU ĐƯỜNG (KÊ ĐƠN)", groupAccent: "#ea580c", bodyColor: "#fff7ed", textDark: true, boxesPerRow: 3, unitPrice: 30000 },
  { id: "tim-046", sku: "TIM-046", name: "Atorvastatin", brand: "Atorvastatin", generic: "Atorvastatin", strength: "10 mg", form: "Viên nén", category: "Tim mạch", cabinetId: "rx_cardio_dm", pack: "Hộp 10 vỉ x 10 viên", retailUnit: "1 vỉ / 1 viên", barcode: "8934360438624", manufacturer: "—", sdk: "TIM-046", isRx: true, groupId: "rx_cardio_dm", groupLabel: "TIM MẠCH – TIỂU ĐƯỜNG (KÊ ĐƠN)", groupAccent: "#ea580c", bodyColor: "#fff7ed", textDark: true, boxesPerRow: 3, unitPrice: 18000 },
  { id: "tim-047", sku: "TIM-047", name: "Rosuvastatin", brand: "Rosuvastatin", generic: "Rosuvastatin", strength: "10 mg", form: "Viên nén", category: "Tim mạch", cabinetId: "rx_cardio_dm", pack: "Hộp 10 vỉ x 10 viên", retailUnit: "1 vỉ / 1 viên", barcode: "8935965266249", manufacturer: "—", sdk: "TIM-047", isRx: true, groupId: "rx_cardio_dm", groupLabel: "TIM MẠCH – TIỂU ĐƯỜNG (KÊ ĐƠN)", groupAccent: "#ea580c", bodyColor: "#fff7ed", textDark: true, boxesPerRow: 3, unitPrice: 18000 },
  { id: "tim-048", sku: "TIM-048", name: "Clopidogrel", brand: "Clopidogrel", generic: "Clopidogrel", strength: "75 mg", form: "Viên nén", category: "Tim mạch", cabinetId: "rx_cardio_dm", pack: "Hộp 10 vỉ x 10 viên", retailUnit: "1 vỉ / 1 viên", barcode: "8936703755911", manufacturer: "—", sdk: "TIM-048", isRx: true, groupId: "rx_cardio_dm", groupLabel: "TIM MẠCH – TIỂU ĐƯỜNG (KÊ ĐƠN)", groupAccent: "#ea580c", bodyColor: "#fff7ed", textDark: true, boxesPerRow: 3, unitPrice: 18000 },
  { id: "tim-049", sku: "TIM-049", name: "Aspirin", brand: "Aspirin", generic: "Aspirin", strength: "81 mg", form: "Viên nén", category: "Tim mạch", cabinetId: "rx_cardio_dm", pack: "Hộp 10 vỉ x 10 viên", retailUnit: "1 vỉ / 1 viên", barcode: "8932619106740", manufacturer: "—", sdk: "TIM-049", isRx: true, groupId: "rx_cardio_dm", groupLabel: "TIM MẠCH – TIỂU ĐƯỜNG (KÊ ĐƠN)", groupAccent: "#ea580c", bodyColor: "#fff7ed", textDark: true, boxesPerRow: 3, unitPrice: 18000 },
  { id: "tim-050", sku: "TIM-050", name: "Nitroglycerin", brand: "Nitroglycerin", generic: "Nitroglycerin", strength: "0.5 mg", form: "Viên ngậm", category: "Tim mạch", cabinetId: "rx_cardio_dm", pack: "Hộp 10 vỉ x 10 viên", retailUnit: "1 vỉ / 1 viên", barcode: "8931494044401", manufacturer: "—", sdk: "TIM-050", isRx: true, groupId: "rx_cardio_dm", groupLabel: "TIM MẠCH – TIỂU ĐƯỜNG (KÊ ĐƠN)", groupAccent: "#ea580c", bodyColor: "#fff7ed", textDark: true, boxesPerRow: 3, unitPrice: 28000 },
  { id: "tim-051", sku: "TIM-051", name: "Concor", brand: "Concor", generic: "Concor", strength: "5 mg", form: "Viên nén", category: "Tim mạch", cabinetId: "rx_cardio_dm", pack: "Hộp 10 vỉ x 10 viên", retailUnit: "1 vỉ / 1 viên", barcode: "8934625215894", manufacturer: "—", sdk: "TIM-051", isRx: true, groupId: "rx_cardio_dm", groupLabel: "TIM MẠCH – TIỂU ĐƯỜNG (KÊ ĐƠN)", groupAccent: "#ea580c", bodyColor: "#fff7ed", textDark: true, boxesPerRow: 3, unitPrice: 18000 },
  { id: "tie-052", sku: "TIỂ-052", name: "Metformin", brand: "Metformin", generic: "Metformin", strength: "500 mg", form: "Viên nén", category: "Tiểu đường", cabinetId: "rx_cardio_dm", pack: "Hộp 10 vỉ x 10 viên", retailUnit: "1 vỉ / 1 viên", barcode: "8938023281948", manufacturer: "—", sdk: "TIỂ-052", isRx: true, groupId: "rx_cardio_dm", groupLabel: "TIM MẠCH – TIỂU ĐƯỜNG (KÊ ĐƠN)", groupAccent: "#ea580c", bodyColor: "#fff7ed", textDark: true, boxesPerRow: 3, unitPrice: 18000 },
  { id: "tie-053", sku: "TIỂ-053", name: "Glimepirid", brand: "Glimepirid", generic: "Glimepirid", strength: "2 mg", form: "Viên nén", category: "Tiểu đường", cabinetId: "rx_cardio_dm", pack: "Hộp 10 vỉ x 10 viên", retailUnit: "1 vỉ / 1 viên", barcode: "8936166103923", manufacturer: "—", sdk: "TIỂ-053", isRx: true, groupId: "rx_cardio_dm", groupLabel: "TIM MẠCH – TIỂU ĐƯỜNG (KÊ ĐƠN)", groupAccent: "#ea580c", bodyColor: "#fff7ed", textDark: true, boxesPerRow: 3, unitPrice: 18000 },
  { id: "tie-054", sku: "TIỂ-054", name: "Gliclazid", brand: "Gliclazid", generic: "Gliclazid", strength: "30 mg", form: "Viên nén", category: "Tiểu đường", cabinetId: "rx_cardio_dm", pack: "Hộp 10 vỉ x 10 viên", retailUnit: "1 vỉ / 1 viên", barcode: "8935380824199", manufacturer: "—", sdk: "TIỂ-054", isRx: true, groupId: "rx_cardio_dm", groupLabel: "TIM MẠCH – TIỂU ĐƯỜNG (KÊ ĐƠN)", groupAccent: "#ea580c", bodyColor: "#fff7ed", textDark: true, boxesPerRow: 3, unitPrice: 18000 },
  { id: "tie-055", sku: "TIỂ-055", name: "Sitagliptin", brand: "Sitagliptin", generic: "Sitagliptin", strength: "100 mg", form: "Viên nén", category: "Tiểu đường", cabinetId: "rx_cardio_dm", pack: "Hộp 10 vỉ x 10 viên", retailUnit: "1 vỉ / 1 viên", barcode: "8935516363385", manufacturer: "—", sdk: "TIỂ-055", isRx: true, groupId: "rx_cardio_dm", groupLabel: "TIM MẠCH – TIỂU ĐƯỜNG (KÊ ĐƠN)", groupAccent: "#ea580c", bodyColor: "#fff7ed", textDark: true, boxesPerRow: 3, unitPrice: 18000 },
  { id: "tie-056", sku: "TIỂ-056", name: "Forxiga", brand: "Forxiga", generic: "Forxiga", strength: "10 mg", form: "Viên nén", category: "Tiểu đường", cabinetId: "rx_cardio_dm", pack: "Hộp 10 vỉ x 10 viên", retailUnit: "1 vỉ / 1 viên", barcode: "8937397623469", manufacturer: "—", sdk: "TIỂ-056", isRx: true, groupId: "rx_cardio_dm", groupLabel: "TIM MẠCH – TIỂU ĐƯỜNG (KÊ ĐƠN)", groupAccent: "#ea580c", bodyColor: "#fff7ed", textDark: true, boxesPerRow: 3, unitPrice: 18000 },
  { id: "tie-057", sku: "TIỂ-057", name: "Jardiance", brand: "Jardiance", generic: "Jardiance", strength: "10 mg", form: "Viên nén", category: "Tiểu đường", cabinetId: "rx_cardio_dm", pack: "Hộp 10 vỉ x 10 viên", retailUnit: "1 vỉ / 1 viên", barcode: "8937044493536", manufacturer: "—", sdk: "TIỂ-057", isRx: true, groupId: "rx_cardio_dm", groupLabel: "TIM MẠCH – TIỂU ĐƯỜNG (KÊ ĐƠN)", groupAccent: "#ea580c", bodyColor: "#fff7ed", textDark: true, boxesPerRow: 3, unitPrice: 18000 },
  { id: "tie-058", sku: "TIỂ-058", name: "Insulin Mixtard", brand: "Insulin Mixtard", generic: "Insulin Mixtard", strength: "100 IU/ml", form: "Bút tiêm", category: "Tiểu đường", cabinetId: "rx_cardio_dm", pack: "1 chai/hộp", retailUnit: "1 đơn vị", barcode: "8937529482044", manufacturer: "—", sdk: "TIỂ-058", isRx: true, groupId: "rx_cardio_dm", groupLabel: "TIM MẠCH – TIỂU ĐƯỜNG (KÊ ĐƠN)", groupAccent: "#ea580c", bodyColor: "#fff7ed", textDark: true, boxesPerRow: 3, unitPrice: 320000 },
  { id: "tie-059", sku: "TIỂ-059", name: "Lantus", brand: "Lantus", generic: "Lantus", strength: "100 IU/ml", form: "Bút tiêm", category: "Tiểu đường", cabinetId: "rx_cardio_dm", pack: "1 chai/hộp", retailUnit: "1 đơn vị", barcode: "8935012652315", manufacturer: "—", sdk: "TIỂ-059", isRx: true, groupId: "rx_cardio_dm", groupLabel: "TIM MẠCH – TIỂU ĐƯỜNG (KÊ ĐƠN)", groupAccent: "#ea580c", bodyColor: "#fff7ed", textDark: true, boxesPerRow: 3, unitPrice: 320000 },
  { id: "tie-060", sku: "TIỂ-060", name: "Accu-Chek", brand: "Accu-Chek", generic: "Accu-Chek", strength: " ", form: "Que thử", category: "Tiểu đường", cabinetId: "rx_cardio_dm", pack: "1 chai/hộp", retailUnit: "1 đơn vị", barcode: "8938007290403", manufacturer: "—", sdk: "TIỂ-060", isRx: true, groupId: "rx_cardio_dm", groupLabel: "TIM MẠCH – TIỂU ĐƯỜNG (KÊ ĐƠN)", groupAccent: "#ea580c", bodyColor: "#fff7ed", textDark: true, boxesPerRow: 3, unitPrice: 80000 },
  { id: "tie-061", sku: "TIỂ-061", name: "Glucophage XR", brand: "Glucophage XR", generic: "Glucophage XR", strength: "750 mg", form: "Viên nén", category: "Tiểu đường", cabinetId: "rx_cardio_dm", pack: "Hộp 10 vỉ x 10 viên", retailUnit: "1 vỉ / 1 viên", barcode: "8936747968755", manufacturer: "—", sdk: "TIỂ-061", isRx: true, groupId: "rx_cardio_dm", groupLabel: "TIM MẠCH – TIỂU ĐƯỜNG (KÊ ĐƠN)", groupAccent: "#ea580c", bodyColor: "#fff7ed", textDark: true, boxesPerRow: 3, unitPrice: 18000 },
  { id: "tie-062", sku: "TIÊ-062", name: "Omeprazol", brand: "Omeprazol", generic: "Omeprazol", strength: "20 mg", form: "Viên nang", category: "Tiêu hóa", cabinetId: "otc_resp_gi", pack: "Hộp 10 vỉ x 10 viên", retailUnit: "1 vỉ / 1 viên", barcode: "8933551438688", manufacturer: "—", sdk: "TIÊ-062", isRx: false, groupId: "otc_resp_gi", groupLabel: "HÔ HẤP – TIÊU HOÁ", groupAccent: "#0d9488", bodyColor: "#ecfdf5", textDark: true, boxesPerRow: 3, unitPrice: 30000 },
  { id: "tie-063", sku: "TIÊ-063", name: "Esomeprazol", brand: "Esomeprazol", generic: "Esomeprazol", strength: "40 mg", form: "Viên nang", category: "Tiêu hóa", cabinetId: "otc_resp_gi", pack: "Hộp 10 vỉ x 10 viên", retailUnit: "1 vỉ / 1 viên", barcode: "8936171094810", manufacturer: "—", sdk: "TIÊ-063", isRx: false, groupId: "otc_resp_gi", groupLabel: "HÔ HẤP – TIÊU HOÁ", groupAccent: "#0d9488", bodyColor: "#ecfdf5", textDark: true, boxesPerRow: 3, unitPrice: 30000 },
  { id: "tie-064", sku: "TIÊ-064", name: "Smecta", brand: "Smecta", generic: "Smecta", strength: "3 g", form: "Gói", category: "Tiêu hóa", cabinetId: "otc_resp_gi", pack: "1 chai/hộp", retailUnit: "1 đơn vị", barcode: "8934111191499", manufacturer: "—", sdk: "TIÊ-064", isRx: false, groupId: "otc_resp_gi", groupLabel: "HÔ HẤP – TIÊU HOÁ", groupAccent: "#0d9488", bodyColor: "#ecfdf5", textDark: true, boxesPerRow: 3, unitPrice: 25000 },
  { id: "tie-065", sku: "TIÊ-065", name: "Enterogermina", brand: "Enterogermina", generic: "Enterogermina", strength: " ", form: "Ống uống", category: "Tiêu hóa", cabinetId: "otc_resp_gi", pack: "1 chai/hộp", retailUnit: "1 đơn vị", barcode: "8932354319764", manufacturer: "—", sdk: "TIÊ-065", isRx: false, groupId: "otc_resp_gi", groupLabel: "HÔ HẤP – TIÊU HOÁ", groupAccent: "#0d9488", bodyColor: "#ecfdf5", textDark: true, boxesPerRow: 3, unitPrice: 20000 },
  { id: "tie-066", sku: "TIÊ-066", name: "Bioflor", brand: "Bioflor", generic: "Bioflor", strength: " ", form: "Gói", category: "Tiêu hóa", cabinetId: "otc_resp_gi", pack: "1 chai/hộp", retailUnit: "1 đơn vị", barcode: "8935118638229", manufacturer: "—", sdk: "TIÊ-066", isRx: false, groupId: "otc_resp_gi", groupLabel: "HÔ HẤP – TIÊU HOÁ", groupAccent: "#0d9488", bodyColor: "#ecfdf5", textDark: true, boxesPerRow: 3, unitPrice: 25000 },
  { id: "tie-067", sku: "TIÊ-067", name: "Loperamid", brand: "Loperamid", generic: "Loperamid", strength: "2 mg", form: "Viên nang", category: "Tiêu hóa", cabinetId: "otc_resp_gi", pack: "Hộp 10 vỉ x 10 viên", retailUnit: "1 vỉ / 1 viên", barcode: "8936852631663", manufacturer: "—", sdk: "TIÊ-067", isRx: false, groupId: "otc_resp_gi", groupLabel: "HÔ HẤP – TIÊU HOÁ", groupAccent: "#0d9488", bodyColor: "#ecfdf5", textDark: true, boxesPerRow: 3, unitPrice: 30000 },
  { id: "tie-068", sku: "TIÊ-068", name: "Motilium", brand: "Motilium", generic: "Motilium", strength: "10 mg", form: "Viên nén", category: "Tiêu hóa", cabinetId: "otc_resp_gi", pack: "Hộp 10 vỉ x 10 viên", retailUnit: "1 vỉ / 1 viên", barcode: "8938593116498", manufacturer: "—", sdk: "TIÊ-068", isRx: false, groupId: "otc_resp_gi", groupLabel: "HÔ HẤP – TIÊU HOÁ", groupAccent: "#0d9488", bodyColor: "#ecfdf5", textDark: true, boxesPerRow: 3, unitPrice: 18000 },
  { id: "tie-069", sku: "TIÊ-069", name: "Gaviscon", brand: "Gaviscon", generic: "Gaviscon", strength: "250 ml", form: "Hỗn dịch", category: "Tiêu hóa", cabinetId: "otc_resp_gi", pack: "1 chai/hộp", retailUnit: "1 đơn vị", barcode: "8932846952857", manufacturer: "—", sdk: "TIÊ-069", isRx: false, groupId: "otc_resp_gi", groupLabel: "HÔ HẤP – TIÊU HOÁ", groupAccent: "#0d9488", bodyColor: "#ecfdf5", textDark: true, boxesPerRow: 3, unitPrice: 38000 },
  { id: "tie-070", sku: "TIÊ-070", name: "Berberin", brand: "Berberin", generic: "Berberin", strength: "10 mg", form: "Viên nén", category: "Tiêu hóa", cabinetId: "otc_resp_gi", pack: "Hộp 10 vỉ x 10 viên", retailUnit: "1 vỉ / 1 viên", barcode: "8939669272051", manufacturer: "—", sdk: "TIÊ-070", isRx: false, groupId: "otc_resp_gi", groupLabel: "HÔ HẤP – TIÊU HOÁ", groupAccent: "#0d9488", bodyColor: "#ecfdf5", textDark: true, boxesPerRow: 3, unitPrice: 18000 },
  { id: "tie-071", sku: "TIÊ-071", name: "Phosphalugel", brand: "Phosphalugel", generic: "Phosphalugel", strength: " ", form: "Gói", category: "Tiêu hóa", cabinetId: "otc_resp_gi", pack: "1 chai/hộp", retailUnit: "1 đơn vị", barcode: "8937752510790", manufacturer: "—", sdk: "TIÊ-071", isRx: false, groupId: "otc_resp_gi", groupLabel: "HÔ HẤP – TIÊU HOÁ", groupAccent: "#0d9488", bodyColor: "#ecfdf5", textDark: true, boxesPerRow: 3, unitPrice: 25000 },
  { id: "tie-072", sku: "TIÊ-072", name: "Duphalac", brand: "Duphalac", generic: "Duphalac", strength: "15 ml", form: "Gói", category: "Tiêu hóa", cabinetId: "otc_resp_gi", pack: "1 chai/hộp", retailUnit: "1 đơn vị", barcode: "8933900695839", manufacturer: "—", sdk: "TIÊ-072", isRx: false, groupId: "otc_resp_gi", groupLabel: "HÔ HẤP – TIÊU HOÁ", groupAccent: "#0d9488", bodyColor: "#ecfdf5", textDark: true, boxesPerRow: 3, unitPrice: 25000 },
  { id: "tie-073", sku: "TIÊ-073", name: "Trimafort", brand: "Trimafort", generic: "Trimafort", strength: " ", form: "Viên nhai", category: "Tiêu hóa", cabinetId: "otc_resp_gi", pack: "Hộp 10 vỉ x 10 viên", retailUnit: "1 vỉ / 1 viên", barcode: "8931778606292", manufacturer: "—", sdk: "TIÊ-073", isRx: false, groupId: "otc_resp_gi", groupLabel: "HÔ HẤP – TIÊU HOÁ", groupAccent: "#0d9488", bodyColor: "#ecfdf5", textDark: true, boxesPerRow: 3, unitPrice: 22000 },
  { id: "vit-074", sku: "VIT-074", name: "Vitamin C", brand: "Vitamin C", generic: "Vitamin C", strength: "500 mg", form: "Viên sủi", category: "Vitamin - Khoáng chất", cabinetId: "side_supp", pack: "Hộp 10 vỉ x 10 viên", retailUnit: "1 vỉ / 1 viên", barcode: "8936276942840", manufacturer: "—", sdk: "VIT-074", isRx: false, groupId: "side_supp", groupLabel: "TPCN – VITAMIN – KHOÁNG CHẤT", groupAccent: "#ca8a04", bodyColor: "#fefce8", textDark: true, boxesPerRow: 3, unitPrice: 26000 },
  { id: "vit-075", sku: "VIT-075", name: "Vitamin 3B", brand: "Vitamin 3B", generic: "Vitamin 3B", strength: " ", form: "Viên nén", category: "Vitamin - Khoáng chất", cabinetId: "side_supp", pack: "Hộp 10 vỉ x 10 viên", retailUnit: "1 vỉ / 1 viên", barcode: "8936064412873", manufacturer: "—", sdk: "VIT-075", isRx: false, groupId: "side_supp", groupLabel: "TPCN – VITAMIN – KHOÁNG CHẤT", groupAccent: "#ca8a04", bodyColor: "#fefce8", textDark: true, boxesPerRow: 3, unitPrice: 18000 },
  { id: "vit-076", sku: "VIT-076", name: "Calci D", brand: "Calci D", generic: "Calci D", strength: " ", form: "Viên nén", category: "Vitamin - Khoáng chất", cabinetId: "side_supp", pack: "Hộp 10 vỉ x 10 viên", retailUnit: "1 vỉ / 1 viên", barcode: "8932799431064", manufacturer: "—", sdk: "VIT-076", isRx: false, groupId: "side_supp", groupLabel: "TPCN – VITAMIN – KHOÁNG CHẤT", groupAccent: "#ca8a04", bodyColor: "#fefce8", textDark: true, boxesPerRow: 3, unitPrice: 18000 },
  { id: "vit-077", sku: "VIT-077", name: "Ferrovit", brand: "Ferrovit", generic: "Ferrovit", strength: " ", form: "Viên nang", category: "Vitamin - Khoáng chất", cabinetId: "side_supp", pack: "Hộp 10 vỉ x 10 viên", retailUnit: "1 vỉ / 1 viên", barcode: "8939599040460", manufacturer: "—", sdk: "VIT-077", isRx: false, groupId: "side_supp", groupLabel: "TPCN – VITAMIN – KHOÁNG CHẤT", groupAccent: "#ca8a04", bodyColor: "#fefce8", textDark: true, boxesPerRow: 3, unitPrice: 30000 },
  { id: "vit-078", sku: "VIT-078", name: "Omega 3", brand: "Omega 3", generic: "Omega 3", strength: "1000 mg", form: "Viên nang", category: "Vitamin - Khoáng chất", cabinetId: "side_supp", pack: "Hộp 10 vỉ x 10 viên", retailUnit: "1 vỉ / 1 viên", barcode: "8933095048199", manufacturer: "—", sdk: "VIT-078", isRx: false, groupId: "side_supp", groupLabel: "TPCN – VITAMIN – KHOÁNG CHẤT", groupAccent: "#ca8a04", bodyColor: "#fefce8", textDark: true, boxesPerRow: 3, unitPrice: 30000 },
  { id: "vit-079", sku: "VIT-079", name: "Magnesi B6", brand: "Magnesi B6", generic: "Magnesi B6", strength: " ", form: "Viên nén", category: "Vitamin - Khoáng chất", cabinetId: "side_supp", pack: "Hộp 10 vỉ x 10 viên", retailUnit: "1 vỉ / 1 viên", barcode: "8931657513544", manufacturer: "—", sdk: "VIT-079", isRx: false, groupId: "side_supp", groupLabel: "TPCN – VITAMIN – KHOÁNG CHẤT", groupAccent: "#ca8a04", bodyColor: "#fefce8", textDark: true, boxesPerRow: 3, unitPrice: 18000 },
  { id: "vit-080", sku: "VIT-080", name: "Kẽm", brand: "Kẽm", generic: "Kẽm", strength: "70 mg", form: "Viên nén", category: "Vitamin - Khoáng chất", cabinetId: "side_supp", pack: "Hộp 10 vỉ x 10 viên", retailUnit: "1 vỉ / 1 viên", barcode: "8933610902598", manufacturer: "—", sdk: "VIT-080", isRx: false, groupId: "side_supp", groupLabel: "TPCN – VITAMIN – KHOÁNG CHẤT", groupAccent: "#ca8a04", bodyColor: "#fefce8", textDark: true, boxesPerRow: 3, unitPrice: 18000 },
  { id: "vit-081", sku: "VIT-081", name: "Vitamin E", brand: "Vitamin E", generic: "Vitamin E", strength: "400 IU", form: "Viên nang", category: "Vitamin - Khoáng chất", cabinetId: "side_supp", pack: "Hộp 10 vỉ x 10 viên", retailUnit: "1 vỉ / 1 viên", barcode: "8934153349585", manufacturer: "—", sdk: "VIT-081", isRx: false, groupId: "side_supp", groupLabel: "TPCN – VITAMIN – KHOÁNG CHẤT", groupAccent: "#ca8a04", bodyColor: "#fefce8", textDark: true, boxesPerRow: 3, unitPrice: 30000 },
  { id: "vit-082", sku: "VIT-082", name: "Multivitamin", brand: "Multivitamin", generic: "Multivitamin", strength: " ", form: "Viên nang", category: "Vitamin - Khoáng chất", cabinetId: "side_supp", pack: "Hộp 10 vỉ x 10 viên", retailUnit: "1 vỉ / 1 viên", barcode: "8936727260287", manufacturer: "—", sdk: "VIT-082", isRx: false, groupId: "side_supp", groupLabel: "TPCN – VITAMIN – KHOÁNG CHẤT", groupAccent: "#ca8a04", bodyColor: "#fefce8", textDark: true, boxesPerRow: 3, unitPrice: 30000 },
  { id: "vit-083", sku: "VIT-083", name: "Prenatal", brand: "Prenatal", generic: "Prenatal", strength: " ", form: "Viên nang", category: "Vitamin - Khoáng chất", cabinetId: "side_supp", pack: "Hộp 10 vỉ x 10 viên", retailUnit: "1 vỉ / 1 viên", barcode: "8937551468169", manufacturer: "—", sdk: "VIT-083", isRx: false, groupId: "side_supp", groupLabel: "TPCN – VITAMIN – KHOÁNG CHẤT", groupAccent: "#ca8a04", bodyColor: "#fefce8", textDark: true, boxesPerRow: 3, unitPrice: 30000 },
  { id: "nho-084", sku: "NHỎ-084", name: "NaCl nhỏ mắt", brand: "NaCl nhỏ mắt", generic: "NaCl nhỏ mắt", strength: "0.9%", form: "Dung dịch nhỏ mắt", category: "Nhỏ mắt", cabinetId: "front_eye", pack: "1 chai/hộp", retailUnit: "1 đơn vị", barcode: "8937796671571", manufacturer: "—", sdk: "NHỎ-084", isRx: false, groupId: "front_eye", groupLabel: "NHỎ MẮT", groupAccent: "#14b8a6", bodyColor: "#f0fdfa", textDark: true, boxesPerRow: 3, unitPrice: 28000 },
  { id: "nho-085", sku: "NHỎ-085", name: "V.Rohto", brand: "V.Rohto", generic: "V.Rohto", strength: "13 ml", form: "Dung dịch nhỏ mắt", category: "Nhỏ mắt", cabinetId: "front_eye", pack: "1 chai/hộp", retailUnit: "1 đơn vị", barcode: "8936739285323", manufacturer: "—", sdk: "NHỎ-085", isRx: false, groupId: "front_eye", groupLabel: "NHỎ MẮT", groupAccent: "#14b8a6", bodyColor: "#f0fdfa", textDark: true, boxesPerRow: 3, unitPrice: 28000 },
  { id: "nho-086", sku: "NHỎ-086", name: "Refresh Tears", brand: "Refresh Tears", generic: "Refresh Tears", strength: "15 ml", form: "Dung dịch nhỏ mắt", category: "Nhỏ mắt", cabinetId: "front_eye", pack: "1 chai/hộp", retailUnit: "1 đơn vị", barcode: "8935352881836", manufacturer: "—", sdk: "NHỎ-086", isRx: false, groupId: "front_eye", groupLabel: "NHỎ MẮT", groupAccent: "#14b8a6", bodyColor: "#f0fdfa", textDark: true, boxesPerRow: 3, unitPrice: 28000 },
  { id: "nho-087", sku: "NHỎ-087", name: "Sancoba", brand: "Sancoba", generic: "Sancoba", strength: "5 ml", form: "Dung dịch nhỏ mắt", category: "Nhỏ mắt", cabinetId: "front_eye", pack: "1 chai/hộp", retailUnit: "1 đơn vị", barcode: "8934704416795", manufacturer: "—", sdk: "NHỎ-087", isRx: false, groupId: "front_eye", groupLabel: "NHỎ MẮT", groupAccent: "#14b8a6", bodyColor: "#f0fdfa", textDark: true, boxesPerRow: 3, unitPrice: 28000 },
  { id: "nho-088", sku: "NHỎ-088", name: "Tobramycin nhỏ mắt", brand: "Tobramycin nhỏ mắt", generic: "Tobramycin nhỏ mắt", strength: "0.3%", form: "Dung dịch nhỏ mắt", category: "Nhỏ mắt", cabinetId: "front_eye", pack: "1 chai/hộp", retailUnit: "1 đơn vị", barcode: "8935923268997", manufacturer: "—", sdk: "NHỎ-088", isRx: false, groupId: "front_eye", groupLabel: "NHỎ MẮT", groupAccent: "#14b8a6", bodyColor: "#f0fdfa", textDark: true, boxesPerRow: 3, unitPrice: 28000 },
  { id: "nho-089", sku: "NHỎ-089", name: "Ofloxacin nhỏ mắt", brand: "Ofloxacin nhỏ mắt", generic: "Ofloxacin nhỏ mắt", strength: "0.3%", form: "Dung dịch nhỏ mắt", category: "Nhỏ mắt", cabinetId: "front_eye", pack: "1 chai/hộp", retailUnit: "1 đơn vị", barcode: "8938427674265", manufacturer: "—", sdk: "NHỎ-089", isRx: false, groupId: "front_eye", groupLabel: "NHỎ MẮT", groupAccent: "#14b8a6", bodyColor: "#f0fdfa", textDark: true, boxesPerRow: 3, unitPrice: 28000 },
  { id: "nho-090", sku: "NHỎ-090", name: "Cloramphenicol nhỏ mắt", brand: "Cloramphenicol nhỏ mắt", generic: "Cloramphenicol nhỏ mắt", strength: "0.4%", form: "Dung dịch nhỏ mắt", category: "Nhỏ mắt", cabinetId: "front_eye", pack: "1 chai/hộp", retailUnit: "1 đơn vị", barcode: "8934204627007", manufacturer: "—", sdk: "NHỎ-090", isRx: false, groupId: "front_eye", groupLabel: "NHỎ MẮT", groupAccent: "#14b8a6", bodyColor: "#f0fdfa", textDark: true, boxesPerRow: 3, unitPrice: 28000 },
  { id: "nho-091", sku: "NHỎ-091", name: "Tears Naturale", brand: "Tears Naturale", generic: "Tears Naturale", strength: "15 ml", form: "Dung dịch nhỏ mắt", category: "Nhỏ mắt", cabinetId: "front_eye", pack: "1 chai/hộp", retailUnit: "1 đơn vị", barcode: "8932590559437", manufacturer: "—", sdk: "NHỎ-091", isRx: false, groupId: "front_eye", groupLabel: "NHỎ MẮT", groupAccent: "#14b8a6", bodyColor: "#f0fdfa", textDark: true, boxesPerRow: 3, unitPrice: 28000 },
  { id: "nho-092", sku: "NHỎ-092", name: "Diclofenac nhỏ mắt", brand: "Diclofenac nhỏ mắt", generic: "Diclofenac nhỏ mắt", strength: "0.1%", form: "Dung dịch nhỏ mắt", category: "Nhỏ mắt", cabinetId: "front_eye", pack: "1 chai/hộp", retailUnit: "1 đơn vị", barcode: "8932454445389", manufacturer: "—", sdk: "NHỎ-092", isRx: false, groupId: "front_eye", groupLabel: "NHỎ MẮT", groupAccent: "#14b8a6", bodyColor: "#f0fdfa", textDark: true, boxesPerRow: 3, unitPrice: 28000 },
  { id: "nho-093", sku: "NHỎ-093", name: "Optive", brand: "Optive", generic: "Optive", strength: "15 ml", form: "Dung dịch nhỏ mắt", category: "Nhỏ mắt", cabinetId: "front_eye", pack: "1 chai/hộp", retailUnit: "1 đơn vị", barcode: "8935103309274", manufacturer: "—", sdk: "NHỎ-093", isRx: false, groupId: "front_eye", groupLabel: "NHỎ MẮT", groupAccent: "#14b8a6", bodyColor: "#f0fdfa", textDark: true, boxesPerRow: 3, unitPrice: 28000 },
  { id: "nho-094", sku: "NHỎ-094", name: "NaCl nhỏ mũi", brand: "NaCl nhỏ mũi", generic: "NaCl nhỏ mũi", strength: "0.9%", form: "Dung dịch", category: "Nhỏ mũi", cabinetId: "front_nose", pack: "1 chai/hộp", retailUnit: "1 đơn vị", barcode: "8938912881190", manufacturer: "—", sdk: "NHỎ-094", isRx: false, groupId: "front_nose", groupLabel: "NHỎ MŨI", groupAccent: "#0ea5e9", bodyColor: "#f0f9ff", textDark: true, boxesPerRow: 3, unitPrice: 30000 },
  { id: "nho-095", sku: "NHỎ-095", name: "Otrivin", brand: "Otrivin", generic: "Otrivin", strength: "0.05%", form: "Dung dịch xịt", category: "Nhỏ mũi", cabinetId: "front_nose", pack: "1 chai/hộp", retailUnit: "1 đơn vị", barcode: "8937338177163", manufacturer: "—", sdk: "NHỎ-095", isRx: false, groupId: "front_nose", groupLabel: "NHỎ MŨI", groupAccent: "#0ea5e9", bodyColor: "#f0f9ff", textDark: true, boxesPerRow: 3, unitPrice: 65000 },
  { id: "nho-096", sku: "NHỎ-096", name: "Xisat", brand: "Xisat", generic: "Xisat", strength: "75 ml", form: "Dung dịch xịt", category: "Nhỏ mũi", cabinetId: "front_nose", pack: "1 chai/hộp", retailUnit: "1 đơn vị", barcode: "8938761712905", manufacturer: "—", sdk: "NHỎ-096", isRx: false, groupId: "front_nose", groupLabel: "NHỎ MŨI", groupAccent: "#0ea5e9", bodyColor: "#f0f9ff", textDark: true, boxesPerRow: 3, unitPrice: 65000 },
  { id: "nho-097", sku: "NHỎ-097", name: "Sterimar", brand: "Sterimar", generic: "Sterimar", strength: "100 ml", form: "Dung dịch xịt", category: "Nhỏ mũi", cabinetId: "front_nose", pack: "1 chai/hộp", retailUnit: "1 đơn vị", barcode: "8939932273031", manufacturer: "—", sdk: "NHỎ-097", isRx: false, groupId: "front_nose", groupLabel: "NHỎ MŨI", groupAccent: "#0ea5e9", bodyColor: "#f0f9ff", textDark: true, boxesPerRow: 3, unitPrice: 65000 },
  { id: "nho-098", sku: "NHỎ-098", name: "Avamys", brand: "Avamys", generic: "Avamys", strength: "120 liều", form: "Xịt mũi", category: "Nhỏ mũi", cabinetId: "front_nose", pack: "1 chai/hộp", retailUnit: "1 đơn vị", barcode: "8939670956599", manufacturer: "—", sdk: "NHỎ-098", isRx: false, groupId: "front_nose", groupLabel: "NHỎ MŨI", groupAccent: "#0ea5e9", bodyColor: "#f0f9ff", textDark: true, boxesPerRow: 3, unitPrice: 52000 },
  { id: "nho-099", sku: "NHỎ-099", name: "Flixonase", brand: "Flixonase", generic: "Flixonase", strength: "120 liều", form: "Xịt mũi", category: "Nhỏ mũi", cabinetId: "front_nose", pack: "1 chai/hộp", retailUnit: "1 đơn vị", barcode: "8932126692516", manufacturer: "—", sdk: "NHỎ-099", isRx: false, groupId: "front_nose", groupLabel: "NHỎ MŨI", groupAccent: "#0ea5e9", bodyColor: "#f0f9ff", textDark: true, boxesPerRow: 3, unitPrice: 52000 },
  { id: "nho-100", sku: "NHỎ-100", name: "Nazal", brand: "Nazal", generic: "Nazal", strength: "15 ml", form: "Dung dịch nhỏ", category: "Nhỏ mũi", cabinetId: "front_nose", pack: "1 chai/hộp", retailUnit: "1 đơn vị", barcode: "8931225093738", manufacturer: "—", sdk: "NHỎ-100", isRx: false, groupId: "front_nose", groupLabel: "NHỎ MŨI", groupAccent: "#0ea5e9", bodyColor: "#f0f9ff", textDark: true, boxesPerRow: 3, unitPrice: 28000 },
  { id: "nho-101", sku: "NHỎ-101", name: "Physiomer", brand: "Physiomer", generic: "Physiomer", strength: "135 ml", form: "Dung dịch xịt", category: "Nhỏ mũi", cabinetId: "front_nose", pack: "1 chai/hộp", retailUnit: "1 đơn vị", barcode: "8934222339466", manufacturer: "—", sdk: "NHỎ-101", isRx: false, groupId: "front_nose", groupLabel: "NHỎ MŨI", groupAccent: "#0ea5e9", bodyColor: "#f0f9ff", textDark: true, boxesPerRow: 3, unitPrice: 65000 },
  { id: "nho-102", sku: "NHỎ-102", name: "Cold-B", brand: "Cold-B", generic: "Cold-B", strength: " ", form: "Dung dịch nhỏ", category: "Nhỏ mũi", cabinetId: "front_nose", pack: "1 chai/hộp", retailUnit: "1 đơn vị", barcode: "8933613217038", manufacturer: "—", sdk: "NHỎ-102", isRx: false, groupId: "front_nose", groupLabel: "NHỎ MŨI", groupAccent: "#0ea5e9", bodyColor: "#f0f9ff", textDark: true, boxesPerRow: 3, unitPrice: 28000 },
  { id: "nho-103", sku: "NHỎ-103", name: "Rhinex", brand: "Rhinex", generic: "Rhinex", strength: " ", form: "Dung dịch xịt", category: "Nhỏ mũi", cabinetId: "front_nose", pack: "1 chai/hộp", retailUnit: "1 đơn vị", barcode: "8932892723875", manufacturer: "—", sdk: "NHỎ-103", isRx: false, groupId: "front_nose", groupLabel: "NHỎ MŨI", groupAccent: "#0ea5e9", bodyColor: "#f0f9ff", textDark: true, boxesPerRow: 3, unitPrice: 65000 },
  { id: "dun-104", sku: "DÙN-104", name: "Betadine", brand: "Betadine", generic: "Betadine", strength: "10%", form: "Dung dịch", category: "Dùng ngoài", cabinetId: "front_topical", pack: "1 chai/hộp", retailUnit: "1 đơn vị", barcode: "8931843723936", manufacturer: "—", sdk: "DÙN-104", isRx: false, groupId: "front_topical", groupLabel: "DÙNG NGOÀI", groupAccent: "#7c3aed", bodyColor: "#f5f3ff", textDark: true, boxesPerRow: 3, unitPrice: 30000 },
  { id: "dun-105", sku: "DÙN-105", name: "Cồn 70 độ", brand: "Cồn 70 độ", generic: "Cồn 70 độ", strength: "500 ml", form: "Dung dịch", category: "Dùng ngoài", cabinetId: "front_topical", pack: "1 chai/hộp", retailUnit: "1 đơn vị", barcode: "8938061480266", manufacturer: "—", sdk: "DÙN-105", isRx: false, groupId: "front_topical", groupLabel: "DÙNG NGOÀI", groupAccent: "#7c3aed", bodyColor: "#f5f3ff", textDark: true, boxesPerRow: 3, unitPrice: 30000 },
  { id: "dun-106", sku: "DÙN-106", name: "Oxy già", brand: "Oxy già", generic: "Oxy già", strength: "3%", form: "Dung dịch", category: "Dùng ngoài", cabinetId: "front_topical", pack: "1 chai/hộp", retailUnit: "1 đơn vị", barcode: "8938466265420", manufacturer: "—", sdk: "DÙN-106", isRx: false, groupId: "front_topical", groupLabel: "DÙNG NGOÀI", groupAccent: "#7c3aed", bodyColor: "#f5f3ff", textDark: true, boxesPerRow: 3, unitPrice: 30000 },
  { id: "dun-107", sku: "DÙN-107", name: "Voltaren gel", brand: "Voltaren gel", generic: "Voltaren gel", strength: "20 g", form: "Gel bôi", category: "Dùng ngoài", cabinetId: "front_topical", pack: "1 chai/hộp", retailUnit: "1 đơn vị", barcode: "8937282721497", manufacturer: "—", sdk: "DÙN-107", isRx: false, groupId: "front_topical", groupLabel: "DÙNG NGOÀI", groupAccent: "#7c3aed", bodyColor: "#f5f3ff", textDark: true, boxesPerRow: 3, unitPrice: 42000 },
  { id: "dun-108", sku: "DÙN-108", name: "Tiger Balm", brand: "Tiger Balm", generic: "Tiger Balm", strength: "20 g", form: "Cao xoa", category: "Dùng ngoài", cabinetId: "front_topical", pack: "1 chai/hộp", retailUnit: "1 đơn vị", barcode: "8936070228762", manufacturer: "—", sdk: "DÙN-108", isRx: false, groupId: "front_topical", groupLabel: "DÙNG NGOÀI", groupAccent: "#7c3aed", bodyColor: "#f5f3ff", textDark: true, boxesPerRow: 3, unitPrice: 30000 },
  { id: "dun-109", sku: "DÙN-109", name: "Silvirin", brand: "Silvirin", generic: "Silvirin", strength: "1%", form: "Kem bôi", category: "Dùng ngoài", cabinetId: "front_topical", pack: "1 chai/hộp", retailUnit: "1 đơn vị", barcode: "8931646685643", manufacturer: "—", sdk: "DÙN-109", isRx: false, groupId: "front_topical", groupLabel: "DÙNG NGOÀI", groupAccent: "#7c3aed", bodyColor: "#f5f3ff", textDark: true, boxesPerRow: 3, unitPrice: 35000 },
  { id: "dun-110", sku: "DÙN-110", name: "Thuốc đỏ", brand: "Thuốc đỏ", generic: "Thuốc đỏ", strength: "20 ml", form: "Dung dịch", category: "Dùng ngoài", cabinetId: "front_topical", pack: "1 chai/hộp", retailUnit: "1 đơn vị", barcode: "8937273584888", manufacturer: "—", sdk: "DÙN-110", isRx: false, groupId: "front_topical", groupLabel: "DÙNG NGOÀI", groupAccent: "#7c3aed", bodyColor: "#f5f3ff", textDark: true, boxesPerRow: 3, unitPrice: 30000 },
  { id: "dun-111", sku: "DÙN-111", name: "Salonpas", brand: "Salonpas", generic: "Salonpas", strength: " ", form: "Miếng dán", category: "Dùng ngoài", cabinetId: "front_topical", pack: "1 chai/hộp", retailUnit: "1 đơn vị", barcode: "8938225497132", manufacturer: "—", sdk: "DÙN-111", isRx: false, groupId: "front_topical", groupLabel: "DÙNG NGOÀI", groupAccent: "#7c3aed", bodyColor: "#f5f3ff", textDark: true, boxesPerRow: 3, unitPrice: 75000 },
  { id: "dun-112", sku: "DÙN-112", name: "Eurax", brand: "Eurax", generic: "Eurax", strength: "10%", form: "Kem bôi", category: "Dùng ngoài", cabinetId: "front_topical", pack: "1 chai/hộp", retailUnit: "1 đơn vị", barcode: "8935837958253", manufacturer: "—", sdk: "DÙN-112", isRx: false, groupId: "front_topical", groupLabel: "DÙNG NGOÀI", groupAccent: "#7c3aed", bodyColor: "#f5f3ff", textDark: true, boxesPerRow: 3, unitPrice: 35000 },
  { id: "dun-113", sku: "DÙN-113", name: "Fucidin", brand: "Fucidin", generic: "Fucidin", strength: " ", form: "Kem bôi", category: "Dùng ngoài", cabinetId: "front_topical", pack: "1 chai/hộp", retailUnit: "1 đơn vị", barcode: "8931183517919", manufacturer: "—", sdk: "DÙN-113", isRx: false, groupId: "front_topical", groupLabel: "DÙNG NGOÀI", groupAccent: "#7c3aed", bodyColor: "#f5f3ff", textDark: true, boxesPerRow: 3, unitPrice: 35000 },
  { id: "dun-114", sku: "DÙN-114", name: "Gentrisone", brand: "Gentrisone", generic: "Gentrisone", strength: " ", form: "Kem bôi", category: "Dùng ngoài", cabinetId: "front_topical", pack: "1 chai/hộp", retailUnit: "1 đơn vị", barcode: "8934639538748", manufacturer: "—", sdk: "DÙN-114", isRx: false, groupId: "front_topical", groupLabel: "DÙNG NGOÀI", groupAccent: "#7c3aed", bodyColor: "#f5f3ff", textDark: true, boxesPerRow: 3, unitPrice: 35000 },
  { id: "dun-115", sku: "DÙN-115", name: "Hirudoid", brand: "Hirudoid", generic: "Hirudoid", strength: " ", form: "Gel bôi", category: "Dùng ngoài", cabinetId: "front_topical", pack: "1 chai/hộp", retailUnit: "1 đơn vị", barcode: "8935377287860", manufacturer: "—", sdk: "DÙN-115", isRx: false, groupId: "front_topical", groupLabel: "DÙNG NGOÀI", groupAccent: "#7c3aed", bodyColor: "#f5f3ff", textDark: true, boxesPerRow: 3, unitPrice: 42000 },
  { id: "gia-116", sku: "GIẢ-116", name: "Paracetamol", brand: "Paracetamol", generic: "Paracetamol", strength: "500 mg", form: "Viên nén", category: "Giảm đau - Hạ sốt", cabinetId: "otc_pain_cold", pack: "Hộp 10 vỉ x 10 viên", retailUnit: "1 vỉ / 1 viên", barcode: "8931344969322", manufacturer: "—", sdk: "GIẢ-116", isRx: false, groupId: "otc_pain_cold", groupLabel: "GIẢM ĐAU – HẠ SỐT – HO CẢM", groupAccent: "#2563eb", bodyColor: "#eff6ff", textDark: true, boxesPerRow: 3, unitPrice: 18000 },
  { id: "gia-117", sku: "GIẢ-117", name: "Efferalgan", brand: "Efferalgan", generic: "Efferalgan", strength: "500 mg", form: "Viên sủi", category: "Giảm đau - Hạ sốt", cabinetId: "otc_pain_cold", pack: "Hộp 10 vỉ x 10 viên", retailUnit: "1 vỉ / 1 viên", barcode: "8932716564291", manufacturer: "—", sdk: "GIẢ-117", isRx: false, groupId: "otc_pain_cold", groupLabel: "GIẢM ĐAU – HẠ SỐT – HO CẢM", groupAccent: "#2563eb", bodyColor: "#eff6ff", textDark: true, boxesPerRow: 3, unitPrice: 26000 },
  { id: "gia-118", sku: "GIẢ-118", name: "Ibuprofen", brand: "Ibuprofen", generic: "Ibuprofen", strength: "400 mg", form: "Viên nén", category: "Giảm đau - Hạ sốt", cabinetId: "otc_pain_cold", pack: "Hộp 10 vỉ x 10 viên", retailUnit: "1 vỉ / 1 viên", barcode: "8934767352311", manufacturer: "—", sdk: "GIẢ-118", isRx: false, groupId: "otc_pain_cold", groupLabel: "GIẢM ĐAU – HẠ SỐT – HO CẢM", groupAccent: "#2563eb", bodyColor: "#eff6ff", textDark: true, boxesPerRow: 3, unitPrice: 18000 },
  { id: "gia-119", sku: "GIẢ-119", name: "Diclofenac", brand: "Diclofenac", generic: "Diclofenac", strength: "50 mg", form: "Viên nén", category: "Giảm đau - Hạ sốt", cabinetId: "otc_pain_cold", pack: "Hộp 10 vỉ x 10 viên", retailUnit: "1 vỉ / 1 viên", barcode: "8931733320564", manufacturer: "—", sdk: "GIẢ-119", isRx: false, groupId: "otc_pain_cold", groupLabel: "GIẢM ĐAU – HẠ SỐT – HO CẢM", groupAccent: "#2563eb", bodyColor: "#eff6ff", textDark: true, boxesPerRow: 3, unitPrice: 18000 },
  { id: "gia-120", sku: "GIẢ-120", name: "Meloxicam", brand: "Meloxicam", generic: "Meloxicam", strength: "7.5 mg", form: "Viên nén", category: "Giảm đau - Hạ sốt", cabinetId: "otc_pain_cold", pack: "Hộp 10 vỉ x 10 viên", retailUnit: "1 vỉ / 1 viên", barcode: "8934389291234", manufacturer: "—", sdk: "GIẢ-120", isRx: false, groupId: "otc_pain_cold", groupLabel: "GIẢM ĐAU – HẠ SỐT – HO CẢM", groupAccent: "#2563eb", bodyColor: "#eff6ff", textDark: true, boxesPerRow: 3, unitPrice: 18000 },
  { id: "gia-121", sku: "GIẢ-121", name: "Celecoxib", brand: "Celecoxib", generic: "Celecoxib", strength: "200 mg", form: "Viên nang", category: "Giảm đau - Hạ sốt", cabinetId: "otc_pain_cold", pack: "Hộp 10 vỉ x 10 viên", retailUnit: "1 vỉ / 1 viên", barcode: "8937774442685", manufacturer: "—", sdk: "GIẢ-121", isRx: false, groupId: "otc_pain_cold", groupLabel: "GIẢM ĐAU – HẠ SỐT – HO CẢM", groupAccent: "#2563eb", bodyColor: "#eff6ff", textDark: true, boxesPerRow: 3, unitPrice: 30000 },
  { id: "gia-122", sku: "GIẢ-122", name: "Naproxen", brand: "Naproxen", generic: "Naproxen", strength: "250 mg", form: "Viên nén", category: "Giảm đau - Hạ sốt", cabinetId: "otc_pain_cold", pack: "Hộp 10 vỉ x 10 viên", retailUnit: "1 vỉ / 1 viên", barcode: "8937392863975", manufacturer: "—", sdk: "GIẢ-122", isRx: false, groupId: "otc_pain_cold", groupLabel: "GIẢM ĐAU – HẠ SỐT – HO CẢM", groupAccent: "#2563eb", bodyColor: "#eff6ff", textDark: true, boxesPerRow: 3, unitPrice: 18000 },
  { id: "gia-123", sku: "GIẢ-123", name: "Panadol", brand: "Panadol", generic: "Panadol", strength: "500 mg", form: "Viên nén", category: "Giảm đau - Hạ sốt", cabinetId: "otc_pain_cold", pack: "Hộp 10 vỉ x 10 viên", retailUnit: "1 vỉ / 1 viên", barcode: "8939584853623", manufacturer: "—", sdk: "GIẢ-123", isRx: false, groupId: "otc_pain_cold", groupLabel: "GIẢM ĐAU – HẠ SỐT – HO CẢM", groupAccent: "#2563eb", bodyColor: "#eff6ff", textDark: true, boxesPerRow: 3, unitPrice: 18000 },
  { id: "gia-124", sku: "GIẢ-124", name: "Alaxan", brand: "Alaxan", generic: "Alaxan", strength: " ", form: "Viên nén", category: "Giảm đau - Hạ sốt", cabinetId: "otc_pain_cold", pack: "Hộp 10 vỉ x 10 viên", retailUnit: "1 vỉ / 1 viên", barcode: "8939400294097", manufacturer: "—", sdk: "GIẢ-124", isRx: false, groupId: "otc_pain_cold", groupLabel: "GIẢM ĐAU – HẠ SỐT – HO CẢM", groupAccent: "#2563eb", bodyColor: "#eff6ff", textDark: true, boxesPerRow: 3, unitPrice: 18000 },
  { id: "gia-125", sku: "GIẢ-125", name: "Alpha Choay", brand: "Alpha Choay", generic: "Alpha Choay", strength: "4200 UI", form: "Viên nén", category: "Giảm đau - Hạ sốt", cabinetId: "otc_pain_cold", pack: "Hộp 10 vỉ x 10 viên", retailUnit: "1 vỉ / 1 viên", barcode: "8934799214811", manufacturer: "—", sdk: "GIẢ-125", isRx: false, groupId: "otc_pain_cold", groupLabel: "GIẢM ĐAU – HẠ SỐT – HO CẢM", groupAccent: "#2563eb", bodyColor: "#eff6ff", textDark: true, boxesPerRow: 3, unitPrice: 18000 },
  { id: "thu-126", sku: "THỰ-126", name: "Boganic", brand: "Boganic", generic: "Boganic", strength: " ", form: "Viên bao", category: "Thực phẩm chức năng", cabinetId: "side_supp", pack: "Hộp 10 vỉ x 10 viên", retailUnit: "1 vỉ / 1 viên", barcode: "8932909981989", manufacturer: "—", sdk: "THỰ-126", isRx: false, groupId: "side_supp", groupLabel: "TPCN – VITAMIN – KHOÁNG CHẤT", groupAccent: "#ca8a04", bodyColor: "#fefce8", textDark: true, boxesPerRow: 3, unitPrice: 28000 },
  { id: "thu-127", sku: "THỰ-127", name: "Hoạt huyết dưỡng não", brand: "Hoạt huyết dưỡng não", generic: "Hoạt huyết dưỡng não", strength: " ", form: "Viên nang", category: "Thực phẩm chức năng", cabinetId: "side_supp", pack: "Hộp 10 vỉ x 10 viên", retailUnit: "1 vỉ / 1 viên", barcode: "8939867870239", manufacturer: "—", sdk: "THỰ-127", isRx: false, groupId: "side_supp", groupLabel: "TPCN – VITAMIN – KHOÁNG CHẤT", groupAccent: "#ca8a04", bodyColor: "#fefce8", textDark: true, boxesPerRow: 3, unitPrice: 30000 },
  { id: "thu-128", sku: "THỰ-128", name: "Glucosamine", brand: "Glucosamine", generic: "Glucosamine", strength: "1500 mg", form: "Viên nén", category: "Thực phẩm chức năng", cabinetId: "side_supp", pack: "Hộp 10 vỉ x 10 viên", retailUnit: "1 vỉ / 1 viên", barcode: "8934235483132", manufacturer: "—", sdk: "THỰ-128", isRx: false, groupId: "side_supp", groupLabel: "TPCN – VITAMIN – KHOÁNG CHẤT", groupAccent: "#ca8a04", bodyColor: "#fefce8", textDark: true, boxesPerRow: 3, unitPrice: 18000 },
  { id: "thu-129", sku: "THỰ-129", name: "Collagen", brand: "Collagen", generic: "Collagen", strength: "5000 mg", form: "Nước uống", category: "Thực phẩm chức năng", cabinetId: "side_supp", pack: "1 chai/hộp", retailUnit: "1 đơn vị", barcode: "8934052726552", manufacturer: "—", sdk: "THỰ-129", isRx: false, groupId: "side_supp", groupLabel: "TPCN – VITAMIN – KHOÁNG CHẤT", groupAccent: "#ca8a04", bodyColor: "#fefce8", textDark: true, boxesPerRow: 3, unitPrice: 22000 },
  { id: "thu-130", sku: "THỰ-130", name: "Yến sào", brand: "Yến sào", generic: "Yến sào", strength: "70 ml", form: "Lọ", category: "Thực phẩm chức năng", cabinetId: "side_supp", pack: "1 chai/hộp", retailUnit: "1 đơn vị", barcode: "8933322207465", manufacturer: "—", sdk: "THỰ-130", isRx: false, groupId: "side_supp", groupLabel: "TPCN – VITAMIN – KHOÁNG CHẤT", groupAccent: "#ca8a04", bodyColor: "#fefce8", textDark: true, boxesPerRow: 3, unitPrice: 65000 },
  { id: "thu-131", sku: "THỰ-131", name: "An cung ngưu", brand: "An cung ngưu", generic: "An cung ngưu", strength: " ", form: "Viên hoàn", category: "Thực phẩm chức năng", cabinetId: "side_supp", pack: "Hộp 10 vỉ x 10 viên", retailUnit: "1 vỉ / 1 viên", barcode: "8938585040965", manufacturer: "—", sdk: "THỰ-131", isRx: false, groupId: "side_supp", groupLabel: "TPCN – VITAMIN – KHOÁNG CHẤT", groupAccent: "#ca8a04", bodyColor: "#fefce8", textDark: true, boxesPerRow: 3, unitPrice: 45000 },
  { id: "thu-132", sku: "THỰ-132", name: "Ginkgo", brand: "Ginkgo", generic: "Ginkgo", strength: "120 mg", form: "Viên nang", category: "Thực phẩm chức năng", cabinetId: "side_supp", pack: "Hộp 10 vỉ x 10 viên", retailUnit: "1 vỉ / 1 viên", barcode: "8936414281658", manufacturer: "—", sdk: "THỰ-132", isRx: false, groupId: "side_supp", groupLabel: "TPCN – VITAMIN – KHOÁNG CHẤT", groupAccent: "#ca8a04", bodyColor: "#fefce8", textDark: true, boxesPerRow: 3, unitPrice: 30000 },
  { id: "thu-133", sku: "THỰ-133", name: "Detox gan", brand: "Detox gan", generic: "Detox gan", strength: " ", form: "Viên nang", category: "Thực phẩm chức năng", cabinetId: "side_supp", pack: "Hộp 10 vỉ x 10 viên", retailUnit: "1 vỉ / 1 viên", barcode: "8931960875533", manufacturer: "—", sdk: "THỰ-133", isRx: false, groupId: "side_supp", groupLabel: "TPCN – VITAMIN – KHOÁNG CHẤT", groupAccent: "#ca8a04", bodyColor: "#fefce8", textDark: true, boxesPerRow: 3, unitPrice: 30000 },
  { id: "thu-134", sku: "THỰ-134", name: "Sâm nhung", brand: "Sâm nhung", generic: "Sâm nhung", strength: " ", form: "Viên nang", category: "Thực phẩm chức năng", cabinetId: "side_supp", pack: "Hộp 10 vỉ x 10 viên", retailUnit: "1 vỉ / 1 viên", barcode: "8938037395892", manufacturer: "—", sdk: "THỰ-134", isRx: false, groupId: "side_supp", groupLabel: "TPCN – VITAMIN – KHOÁNG CHẤT", groupAccent: "#ca8a04", bodyColor: "#fefce8", textDark: true, boxesPerRow: 3, unitPrice: 30000 },
  { id: "thu-135", sku: "THỰ-135", name: "Evening Primrose", brand: "Evening Primrose", generic: "Evening Primrose", strength: " ", form: "Viên nang", category: "Thực phẩm chức năng", cabinetId: "side_supp", pack: "Hộp 10 vỉ x 10 viên", retailUnit: "1 vỉ / 1 viên", barcode: "8934559394654", manufacturer: "—", sdk: "THỰ-135", isRx: false, groupId: "side_supp", groupLabel: "TPCN – VITAMIN – KHOÁNG CHẤT", groupAccent: "#ca8a04", bodyColor: "#fefce8", textDark: true, boxesPerRow: 3, unitPrice: 30000 },
  { id: "dun-136", sku: "DỤN-136", name: "Khẩu trang y tế", brand: "Khẩu trang y tế", generic: "Khẩu trang y tế", strength: " ", form: "Hộp", category: "Dụng cụ y tế", cabinetId: "side_cosmetic", pack: "1 chai/hộp", retailUnit: "1 đơn vị", barcode: "8939977201346", manufacturer: "—", sdk: "DỤN-136", isRx: false, groupId: "side_cosmetic", groupLabel: "MỸ PHẨM – DỤNG CỤ Y TẾ", groupAccent: "#db2777", bodyColor: "#fdf2f8", textDark: true, boxesPerRow: 3, unitPrice: 80000 },
  { id: "dun-137", sku: "DỤN-137", name: "Nhiệt kế điện tử", brand: "Nhiệt kế điện tử", generic: "Nhiệt kế điện tử", strength: " ", form: "Thiết bị", category: "Dụng cụ y tế", cabinetId: "side_cosmetic", pack: "1 chai/hộp", retailUnit: "1 đơn vị", barcode: "8933750817885", manufacturer: "—", sdk: "DỤN-137", isRx: false, groupId: "side_cosmetic", groupLabel: "MỸ PHẨM – DỤNG CỤ Y TẾ", groupAccent: "#db2777", bodyColor: "#fdf2f8", textDark: true, boxesPerRow: 3, unitPrice: 250000 },
  { id: "dun-138", sku: "DỤN-138", name: "Máy đo huyết áp", brand: "Máy đo huyết áp", generic: "Máy đo huyết áp", strength: " ", form: "Thiết bị", category: "Dụng cụ y tế", cabinetId: "side_cosmetic", pack: "1 chai/hộp", retailUnit: "1 đơn vị", barcode: "8936704573873", manufacturer: "—", sdk: "DỤN-138", isRx: false, groupId: "side_cosmetic", groupLabel: "MỸ PHẨM – DỤNG CỤ Y TẾ", groupAccent: "#db2777", bodyColor: "#fdf2f8", textDark: true, boxesPerRow: 3, unitPrice: 250000 },
  { id: "dun-139", sku: "DỤN-139", name: "Bông y tế", brand: "Bông y tế", generic: "Bông y tế", strength: " ", form: "Gói", category: "Dụng cụ y tế", cabinetId: "side_cosmetic", pack: "1 chai/hộp", retailUnit: "1 đơn vị", barcode: "8931900906663", manufacturer: "—", sdk: "DỤN-139", isRx: false, groupId: "side_cosmetic", groupLabel: "MỸ PHẨM – DỤNG CỤ Y TẾ", groupAccent: "#db2777", bodyColor: "#fdf2f8", textDark: true, boxesPerRow: 3, unitPrice: 25000 },
  { id: "dun-140", sku: "DỤN-140", name: "Gạc y tế", brand: "Gạc y tế", generic: "Gạc y tế", strength: " ", form: "Hộp", category: "Dụng cụ y tế", cabinetId: "side_cosmetic", pack: "1 chai/hộp", retailUnit: "1 đơn vị", barcode: "8931845251532", manufacturer: "—", sdk: "DỤN-140", isRx: false, groupId: "side_cosmetic", groupLabel: "MỸ PHẨM – DỤNG CỤ Y TẾ", groupAccent: "#db2777", bodyColor: "#fdf2f8", textDark: true, boxesPerRow: 3, unitPrice: 80000 },
  { id: "kha-142", sku: "KHÁ-142", name: "Augmentin", brand: "Augmentin", generic: "Augmentin", strength: "500/62.5 mg", form: "Gói", category: "Kháng sinh", cabinetId: "rx_abx", pack: "Hộp 10 gói", retailUnit: "1 gói", barcode: "8930000000000", manufacturer: "—", sdk: "KHÁ-142", isRx: true, isAntibiotic: true, groupId: "rx_abx", groupLabel: "KHÁNG SINH (KÊ ĐƠN)", groupAccent: "#dc2626", bodyColor: "#fef2f2", textDark: true, boxesPerRow: 3, unitPrice: 25000 },
  { id: "kha-143", sku: "KHÁ-143", name: "Augmentin", brand: "Augmentin", generic: "Augmentin", strength: "250 mg", form: "Bột pha hỗn dịch", category: "Kháng sinh", cabinetId: "rx_abx", pack: "1 chai/hộp", retailUnit: "1 đơn vị", barcode: "8930000000000", manufacturer: "—", sdk: "KHÁ-143", isRx: true, isAntibiotic: true, groupId: "rx_abx", groupLabel: "KHÁNG SINH (KÊ ĐƠN)", groupAccent: "#dc2626", bodyColor: "#fef2f2", textDark: true, boxesPerRow: 3, unitPrice: 22000 },
  { id: "kha-144", sku: "KHÁ-144", name: "Klamentin", brand: "Klamentin", generic: "Klamentin", strength: "250 mg", form: "Gói", category: "Kháng sinh", cabinetId: "rx_abx", pack: "Hộp 10 gói", retailUnit: "1 gói", barcode: "8930000000000", manufacturer: "—", sdk: "KHÁ-144", isRx: true, isAntibiotic: true, groupId: "rx_abx", groupLabel: "KHÁNG SINH (KÊ ĐƠN)", groupAccent: "#dc2626", bodyColor: "#fef2f2", textDark: true, boxesPerRow: 3, unitPrice: 25000 },
  { id: "kha-145", sku: "KHÁ-145", name: "Zinnat", brand: "Zinnat", generic: "Zinnat", strength: "125 mg", form: "Bột pha hỗn dịch", category: "Kháng sinh", cabinetId: "rx_abx", pack: "1 chai/hộp", retailUnit: "1 đơn vị", barcode: "8930000000000", manufacturer: "—", sdk: "KHÁ-145", isRx: true, isAntibiotic: true, groupId: "rx_abx", groupLabel: "KHÁNG SINH (KÊ ĐƠN)", groupAccent: "#dc2626", bodyColor: "#fef2f2", textDark: true, boxesPerRow: 3, unitPrice: 22000 },
  { id: "kha-146", sku: "KHÁ-146", name: "Cefixim", brand: "Cefixim", generic: "Cefixim", strength: "100 mg", form: "Gói", category: "Kháng sinh", cabinetId: "rx_abx", pack: "Hộp 10 gói", retailUnit: "1 gói", barcode: "8930000000000", manufacturer: "—", sdk: "KHÁ-146", isRx: true, isAntibiotic: true, groupId: "rx_abx", groupLabel: "KHÁNG SINH (KÊ ĐƠN)", groupAccent: "#dc2626", bodyColor: "#fef2f2", textDark: true, boxesPerRow: 3, unitPrice: 25000 },
  { id: "kha-147", sku: "KHÁ-147", name: "Azithromycin", brand: "Azithromycin", generic: "Azithromycin", strength: "200 mg", form: "Bột pha hỗn dịch", category: "Kháng sinh", cabinetId: "rx_abx", pack: "1 chai/hộp", retailUnit: "1 đơn vị", barcode: "8930000000000", manufacturer: "—", sdk: "KHÁ-147", isRx: true, isAntibiotic: true, groupId: "rx_abx", groupLabel: "KHÁNG SINH (KÊ ĐƠN)", groupAccent: "#dc2626", bodyColor: "#fef2f2", textDark: true, boxesPerRow: 3, unitPrice: 22000 },
  { id: "gia-148", sku: "GIẢ-148", name: "Hapacol Kids", brand: "Hapacol Kids", generic: "Hapacol Kids", strength: "250 mg", form: "Gói", category: "Giảm đau - Hạ sốt", cabinetId: "otc_pain_cold", pack: "Hộp 10 gói", retailUnit: "1 gói", barcode: "8930000000000", manufacturer: "—", sdk: "GIẢ-148", isRx: false, groupId: "otc_pain_cold", groupLabel: "GIẢM ĐAU – HẠ SỐT – HO CẢM", groupAccent: "#2563eb", bodyColor: "#eff6ff", textDark: true, boxesPerRow: 3, unitPrice: 25000 },
  { id: "gia-149", sku: "GIẢ-149", name: "Efferalgan", brand: "Efferalgan", generic: "Efferalgan", strength: "150 mg", form: "Gói", category: "Giảm đau - Hạ sốt", cabinetId: "otc_pain_cold", pack: "Hộp 10 gói", retailUnit: "1 gói", barcode: "8930000000000", manufacturer: "—", sdk: "GIẢ-149", isRx: false, groupId: "otc_pain_cold", groupLabel: "GIẢM ĐAU – HẠ SỐT – HO CẢM", groupAccent: "#2563eb", bodyColor: "#eff6ff", textDark: true, boxesPerRow: 3, unitPrice: 25000 },
  { id: "tie-150", sku: "TIÊ-150", name: "Oresol", brand: "Oresol", generic: "Oresol", strength: "27.9 g", form: "Gói", category: "Tiêu hóa", cabinetId: "otc_resp_gi", pack: "Hộp 10 gói", retailUnit: "1 gói", barcode: "8930000000000", manufacturer: "—", sdk: "TIÊ-150", isRx: false, groupId: "otc_resp_gi", groupLabel: "HÔ HẤP – TIÊU HOÁ", groupAccent: "#0d9488", bodyColor: "#ecfdf5", textDark: true, boxesPerRow: 3, unitPrice: 25000 },
  { id: "tie-151", sku: "TIÊ-151", name: "Smecta", brand: "Smecta", generic: "Smecta", strength: "3 g", form: "Gói", category: "Tiêu hóa", cabinetId: "otc_resp_gi", pack: "Hộp 10 gói", retailUnit: "1 gói", barcode: "8930000000000", manufacturer: "—", sdk: "TIÊ-151", isRx: false, groupId: "otc_resp_gi", groupLabel: "HÔ HẤP – TIÊU HOÁ", groupAccent: "#0d9488", bodyColor: "#ecfdf5", textDark: true, boxesPerRow: 3, unitPrice: 25000 },
  { id: "tie-152", sku: "TIÊ-152", name: "Bioflora", brand: "Bioflora", generic: "Bioflora", strength: "100 mg", form: "Gói", category: "Tiêu hóa", cabinetId: "otc_resp_gi", pack: "Hộp 10 gói", retailUnit: "1 gói", barcode: "8930000000000", manufacturer: "—", sdk: "TIÊ-152", isRx: false, groupId: "otc_resp_gi", groupLabel: "HÔ HẤP – TIÊU HOÁ", groupAccent: "#0d9488", bodyColor: "#ecfdf5", textDark: true, boxesPerRow: 3, unitPrice: 25000 },
  { id: "tie-153", sku: "TIÊ-153", name: "Enterogermina", brand: "Enterogermina", generic: "Enterogermina", strength: "2 tỷ bào tử", form: "Ống uống", category: "Tiêu hóa", cabinetId: "otc_resp_gi", pack: "Hộp 20 ống", retailUnit: "1 ống", barcode: "8930000000000", manufacturer: "—", sdk: "TIÊ-153", isRx: false, groupId: "otc_resp_gi", groupLabel: "HÔ HẤP – TIÊU HOÁ", groupAccent: "#0d9488", bodyColor: "#ecfdf5", textDark: true, boxesPerRow: 3, unitPrice: 20000 },
  { id: "tie-154", sku: "TIÊ-154", name: "BioGaia", brand: "BioGaia", generic: "BioGaia", strength: "5 ml", form: "Nhỏ giọt", category: "Tiêu hóa", cabinetId: "otc_resp_gi", pack: "1 chai/hộp", retailUnit: "1 đơn vị", barcode: "8930000000000", manufacturer: "—", sdk: "TIÊ-154", isRx: false, groupId: "otc_resp_gi", groupLabel: "HÔ HẤP – TIÊU HOÁ", groupAccent: "#0d9488", bodyColor: "#ecfdf5", textDark: true, boxesPerRow: 3, unitPrice: 28000 },
  { id: "ho-155", sku: "HO -155", name: "Astex", brand: "Astex", generic: "Astex", strength: "90 ml", form: "Siro", category: "Ho cảm", cabinetId: "otc_pain_cold", pack: "1 chai/hộp", retailUnit: "1 đơn vị", barcode: "8930000000000", manufacturer: "—", sdk: "HO -155", isRx: false, groupId: "otc_pain_cold", groupLabel: "GIẢM ĐAU – HẠ SỐT – HO CẢM", groupAccent: "#2563eb", bodyColor: "#eff6ff", textDark: true, boxesPerRow: 3, unitPrice: 45000 },
  { id: "ho-156", sku: "HÔ -156", name: "Prospan", brand: "Prospan", generic: "Prospan", strength: "100 ml", form: "Siro", category: "Hô hấp", cabinetId: "otc_resp_gi", pack: "1 chai/hộp", retailUnit: "1 đơn vị", barcode: "8930000000000", manufacturer: "—", sdk: "HÔ -156", isRx: false, groupId: "otc_resp_gi", groupLabel: "HÔ HẤP – TIÊU HOÁ", groupAccent: "#0d9488", bodyColor: "#ecfdf5", textDark: true, boxesPerRow: 3, unitPrice: 45000 },
  { id: "ho-157", sku: "HO -157", name: "Aerius", brand: "Aerius", generic: "Aerius", strength: "0.5 mg/ml", form: "Siro", category: "Ho cảm", cabinetId: "otc_pain_cold", pack: "1 chai/hộp", retailUnit: "1 đơn vị", barcode: "8930000000000", manufacturer: "—", sdk: "HO -157", isRx: false, groupId: "otc_pain_cold", groupLabel: "GIẢM ĐAU – HẠ SỐT – HO CẢM", groupAccent: "#2563eb", bodyColor: "#eff6ff", textDark: true, boxesPerRow: 3, unitPrice: 45000 },
  { id: "ho-158", sku: "HO -158", name: "Zyrtec", brand: "Zyrtec", generic: "Zyrtec", strength: "1 mg/ml", form: "Siro", category: "Ho cảm", cabinetId: "otc_pain_cold", pack: "1 chai/hộp", retailUnit: "1 đơn vị", barcode: "8930000000000", manufacturer: "—", sdk: "HO -158", isRx: false, groupId: "otc_pain_cold", groupLabel: "GIẢM ĐAU – HẠ SỐT – HO CẢM", groupAccent: "#2563eb", bodyColor: "#eff6ff", textDark: true, boxesPerRow: 3, unitPrice: 45000 },
  { id: "ho-159", sku: "HÔ -159", name: "Ventolin", brand: "Ventolin", generic: "Ventolin", strength: "2 mg/5ml", form: "Siro", category: "Hô hấp", cabinetId: "otc_resp_gi", pack: "1 chai/hộp", retailUnit: "1 đơn vị", barcode: "8930000000000", manufacturer: "—", sdk: "HÔ -159", isRx: false, groupId: "otc_resp_gi", groupLabel: "HÔ HẤP – TIÊU HOÁ", groupAccent: "#0d9488", bodyColor: "#ecfdf5", textDark: true, boxesPerRow: 3, unitPrice: 45000 },
  { id: "ho-160", sku: "HÔ -160", name: "Bisolvon", brand: "Bisolvon", generic: "Bisolvon", strength: "4 mg/5ml", form: "Siro", category: "Hô hấp", cabinetId: "otc_resp_gi", pack: "1 chai/hộp", retailUnit: "1 đơn vị", barcode: "8930000000000", manufacturer: "—", sdk: "HÔ -160", isRx: false, groupId: "otc_resp_gi", groupLabel: "HÔ HẤP – TIÊU HOÁ", groupAccent: "#0d9488", bodyColor: "#ecfdf5", textDark: true, boxesPerRow: 3, unitPrice: 45000 },
  { id: "ho-161", sku: "HÔ -161", name: "Pulmicort Respules", brand: "Pulmicort Respules", generic: "Pulmicort Respules", strength: "0.5 mg", form: "Ống khí dung", category: "Hô hấp", cabinetId: "otc_resp_gi", pack: "Hộp 20 ống", retailUnit: "1 ống", barcode: "8930000000000", manufacturer: "—", sdk: "HÔ -161", isRx: false, groupId: "otc_resp_gi", groupLabel: "HÔ HẤP – TIÊU HOÁ", groupAccent: "#0d9488", bodyColor: "#ecfdf5", textDark: true, boxesPerRow: 3, unitPrice: 85000 },
  { id: "ped-162", sku: "PED-162", name: "Augmentin", brand: "Augmentin", generic: "Augmentin", strength: "250mg/31.25mg", form: "Bột pha hỗn dịch uống", category: "Kháng sinh", cabinetId: "rx_abx", pack: "1 chai/hộp", retailUnit: "1 chai", barcode: "8930000000000", manufacturer: "—", sdk: "PED-162", isRx: true, isAntibiotic: true, groupId: "rx_abx", groupLabel: "KHÁNG SINH (KÊ ĐƠN)", groupAccent: "#dc2626", bodyColor: "#fef2f2", textDark: true, boxesPerRow: 3, unitPrice: 22000 },
  { id: "ped-163", sku: "PED-163", name: "Augmentin", brand: "Augmentin", generic: "Augmentin", strength: "500mg/62.5mg", form: "Gói", category: "Kháng sinh", cabinetId: "rx_abx", pack: "Hộp 10 gói", retailUnit: "1 gói", barcode: "8930000000000", manufacturer: "—", sdk: "PED-163", isRx: true, isAntibiotic: true, groupId: "rx_abx", groupLabel: "KHÁNG SINH (KÊ ĐƠN)", groupAccent: "#dc2626", bodyColor: "#fef2f2", textDark: true, boxesPerRow: 3, unitPrice: 25000 },
  { id: "ped-164", sku: "PED-164", name: "Zinnat", brand: "Zinnat", generic: "Zinnat", strength: "125mg", form: "Bột pha hỗn dịch", category: "Kháng sinh", cabinetId: "rx_abx", pack: "1 chai/hộp", retailUnit: "1 chai", barcode: "8930000000000", manufacturer: "—", sdk: "PED-164", isRx: true, isAntibiotic: true, groupId: "rx_abx", groupLabel: "KHÁNG SINH (KÊ ĐƠN)", groupAccent: "#dc2626", bodyColor: "#fef2f2", textDark: true, boxesPerRow: 3, unitPrice: 22000 },
  { id: "ped-165", sku: "PED-165", name: "Cefixim", brand: "Cefixim", generic: "Cefixim", strength: "100mg", form: "Gói", category: "Kháng sinh", cabinetId: "rx_abx", pack: "Hộp 10 gói", retailUnit: "1 gói", barcode: "8930000000000", manufacturer: "—", sdk: "PED-165", isRx: true, isAntibiotic: true, groupId: "rx_abx", groupLabel: "KHÁNG SINH (KÊ ĐƠN)", groupAccent: "#dc2626", bodyColor: "#fef2f2", textDark: true, boxesPerRow: 3, unitPrice: 25000 },
  { id: "ped-166", sku: "PED-166", name: "Azithromycin", brand: "Azithromycin", generic: "Azithromycin", strength: "200mg/5ml", form: "Bột pha hỗn dịch", category: "Kháng sinh", cabinetId: "rx_abx", pack: "1 chai/hộp", retailUnit: "1 chai", barcode: "8930000000000", manufacturer: "—", sdk: "PED-166", isRx: true, isAntibiotic: true, groupId: "rx_abx", groupLabel: "KHÁNG SINH (KÊ ĐƠN)", groupAccent: "#dc2626", bodyColor: "#fef2f2", textDark: true, boxesPerRow: 3, unitPrice: 22000 },
  { id: "ped-167", sku: "PED-167", name: "Klamentin", brand: "Klamentin", generic: "Klamentin", strength: "250mg", form: "Gói", category: "Kháng sinh", cabinetId: "rx_abx", pack: "Hộp 10 gói", retailUnit: "1 gói", barcode: "8930000000000", manufacturer: "—", sdk: "PED-167", isRx: true, isAntibiotic: true, groupId: "rx_abx", groupLabel: "KHÁNG SINH (KÊ ĐƠN)", groupAccent: "#dc2626", bodyColor: "#fef2f2", textDark: true, boxesPerRow: 3, unitPrice: 25000 },
  { id: "ped-168", sku: "PED-168", name: "Hapacol Kids", brand: "Hapacol Kids", generic: "Hapacol Kids", strength: "150mg", form: "Gói", category: "Giảm đau - Hạ sốt", cabinetId: "otc_pain_cold", pack: "Hộp 10 gói", retailUnit: "1 gói", barcode: "8930000000000", manufacturer: "—", sdk: "PED-168", isRx: false, groupId: "otc_pain_cold", groupLabel: "GIẢM ĐAU – HẠ SỐT – HO CẢM", groupAccent: "#2563eb", bodyColor: "#eff6ff", textDark: true, boxesPerRow: 3, unitPrice: 25000 },
  { id: "ped-169", sku: "PED-169", name: "Efferalgan", brand: "Efferalgan", generic: "Efferalgan", strength: "150mg", form: "Gói", category: "Giảm đau - Hạ sốt", cabinetId: "otc_pain_cold", pack: "Hộp 10 gói", retailUnit: "1 gói", barcode: "8930000000000", manufacturer: "—", sdk: "PED-169", isRx: false, groupId: "otc_pain_cold", groupLabel: "GIẢM ĐAU – HẠ SỐT – HO CẢM", groupAccent: "#2563eb", bodyColor: "#eff6ff", textDark: true, boxesPerRow: 3, unitPrice: 25000 },
  { id: "ped-170", sku: "PED-170", name: "Oresol", brand: "Oresol", generic: "Oresol", strength: "27.9g", form: "Gói", category: "Tiêu hóa", cabinetId: "otc_resp_gi", pack: "Hộp 10 gói", retailUnit: "1 gói", barcode: "8930000000000", manufacturer: "—", sdk: "PED-170", isRx: false, groupId: "otc_resp_gi", groupLabel: "HÔ HẤP – TIÊU HOÁ", groupAccent: "#0d9488", bodyColor: "#ecfdf5", textDark: true, boxesPerRow: 3, unitPrice: 25000 },
  { id: "ped-171", sku: "PED-171", name: "Smecta", brand: "Smecta", generic: "Smecta", strength: "3g", form: "Gói", category: "Tiêu hóa", cabinetId: "otc_resp_gi", pack: "Hộp 10 gói", retailUnit: "1 gói", barcode: "8930000000000", manufacturer: "—", sdk: "PED-171", isRx: false, groupId: "otc_resp_gi", groupLabel: "HÔ HẤP – TIÊU HOÁ", groupAccent: "#0d9488", bodyColor: "#ecfdf5", textDark: true, boxesPerRow: 3, unitPrice: 25000 },
  { id: "ped-172", sku: "PED-172", name: "Bioflora", brand: "Bioflora", generic: "Bioflora", strength: "100mg", form: "Gói", category: "Tiêu hóa", cabinetId: "otc_resp_gi", pack: "Hộp 10 gói", retailUnit: "1 gói", barcode: "8930000000000", manufacturer: "—", sdk: "PED-172", isRx: false, groupId: "otc_resp_gi", groupLabel: "HÔ HẤP – TIÊU HOÁ", groupAccent: "#0d9488", bodyColor: "#ecfdf5", textDark: true, boxesPerRow: 3, unitPrice: 25000 },
  { id: "ped-173", sku: "PED-173", name: "Enterogermina", brand: "Enterogermina", generic: "Enterogermina", strength: "2 tỷ bào tử", form: "Ống uống", category: "Tiêu hóa", cabinetId: "otc_resp_gi", pack: "Hộp 10-20 ống", retailUnit: "1 ống", barcode: "8930000000000", manufacturer: "—", sdk: "PED-173", isRx: false, groupId: "otc_resp_gi", groupLabel: "HÔ HẤP – TIÊU HOÁ", groupAccent: "#0d9488", bodyColor: "#ecfdf5", textDark: true, boxesPerRow: 3, unitPrice: 20000 },
  { id: "ped-174", sku: "PED-174", name: "BioGaia", brand: "BioGaia", generic: "BioGaia", strength: "5ml", form: "Ống nhỏ giọt", category: "Tiêu hóa", cabinetId: "otc_resp_gi", pack: "Hộp 10-20 ống", retailUnit: "1 ống", barcode: "8930000000000", manufacturer: "—", sdk: "PED-174", isRx: false, groupId: "otc_resp_gi", groupLabel: "HÔ HẤP – TIÊU HOÁ", groupAccent: "#0d9488", bodyColor: "#ecfdf5", textDark: true, boxesPerRow: 3, unitPrice: 28000 },
  { id: "ped-175", sku: "PED-175", name: "Pulmicort Respules", brand: "Pulmicort Respules", generic: "Pulmicort Respules", strength: "0.5mg/2ml", form: "Ống khí dung", category: "Hô hấp", cabinetId: "otc_resp_gi", pack: "Hộp 10-20 ống", retailUnit: "1 ống", barcode: "8930000000000", manufacturer: "—", sdk: "PED-175", isRx: false, groupId: "otc_resp_gi", groupLabel: "HÔ HẤP – TIÊU HOÁ", groupAccent: "#0d9488", bodyColor: "#ecfdf5", textDark: true, boxesPerRow: 3, unitPrice: 85000 },
  { id: "ped-176", sku: "PED-176", name: "Ventolin", brand: "Ventolin", generic: "Ventolin", strength: "2mg/5ml", form: "Siro", category: "Hô hấp", cabinetId: "otc_resp_gi", pack: "1 chai/hộp", retailUnit: "1 chai", barcode: "8930000000000", manufacturer: "—", sdk: "PED-176", isRx: false, groupId: "otc_resp_gi", groupLabel: "HÔ HẤP – TIÊU HOÁ", groupAccent: "#0d9488", bodyColor: "#ecfdf5", textDark: true, boxesPerRow: 3, unitPrice: 45000 },
  { id: "ped-177", sku: "PED-177", name: "Bisolvon Kids", brand: "Bisolvon Kids", generic: "Bisolvon Kids", strength: "4mg/5ml", form: "Siro", category: "Hô hấp", cabinetId: "otc_resp_gi", pack: "1 chai/hộp", retailUnit: "1 chai", barcode: "8930000000000", manufacturer: "—", sdk: "PED-177", isRx: false, groupId: "otc_resp_gi", groupLabel: "HÔ HẤP – TIÊU HOÁ", groupAccent: "#0d9488", bodyColor: "#ecfdf5", textDark: true, boxesPerRow: 3, unitPrice: 45000 },
  { id: "ped-178", sku: "PED-178", name: "Prospan Kids", brand: "Prospan Kids", generic: "Prospan Kids", strength: "100ml", form: "Siro", category: "Ho cảm", cabinetId: "otc_pain_cold", pack: "1 chai/hộp", retailUnit: "1 chai", barcode: "8930000000000", manufacturer: "—", sdk: "PED-178", isRx: false, groupId: "otc_pain_cold", groupLabel: "GIẢM ĐAU – HẠ SỐT – HO CẢM", groupAccent: "#2563eb", bodyColor: "#eff6ff", textDark: true, boxesPerRow: 3, unitPrice: 45000 },
  { id: "ped-179", sku: "PED-179", name: "Astex", brand: "Astex", generic: "Astex", strength: "90ml", form: "Siro", category: "Ho cảm", cabinetId: "otc_pain_cold", pack: "1 chai/hộp", retailUnit: "1 chai", barcode: "8930000000000", manufacturer: "—", sdk: "PED-179", isRx: false, groupId: "otc_pain_cold", groupLabel: "GIẢM ĐAU – HẠ SỐT – HO CẢM", groupAccent: "#2563eb", bodyColor: "#eff6ff", textDark: true, boxesPerRow: 3, unitPrice: 45000 },
  { id: "ped-180", sku: "PED-180", name: "Aerius", brand: "Aerius", generic: "Aerius", strength: "0.5mg/ml", form: "Siro", category: "Ho cảm", cabinetId: "otc_pain_cold", pack: "1 chai/hộp", retailUnit: "1 chai", barcode: "8930000000000", manufacturer: "—", sdk: "PED-180", isRx: false, groupId: "otc_pain_cold", groupLabel: "GIẢM ĐAU – HẠ SỐT – HO CẢM", groupAccent: "#2563eb", bodyColor: "#eff6ff", textDark: true, boxesPerRow: 3, unitPrice: 45000 },
  { id: "ped-181", sku: "PED-181", name: "Zyrtec", brand: "Zyrtec", generic: "Zyrtec", strength: "1mg/ml", form: "Siro", category: "Ho cảm", cabinetId: "otc_pain_cold", pack: "1 chai/hộp", retailUnit: "1 chai", barcode: "8930000000000", manufacturer: "—", sdk: "PED-181", isRx: false, groupId: "otc_pain_cold", groupLabel: "GIẢM ĐAU – HẠ SỐT – HO CẢM", groupAccent: "#2563eb", bodyColor: "#eff6ff", textDark: true, boxesPerRow: 3, unitPrice: 45000 },
];

// SCENE_DRUGS (subset shown in 3D scene) ---
export const SCENE_DRUGS: DrugSpec[] = [
  { id: "gia-116", sku: "GIẢ-116", name: "Paracetamol", brand: "Paracetamol", generic: "Paracetamol", strength: "500 mg", form: "Viên nén", category: "Giảm đau - Hạ sốt", cabinetId: "otc_pain_cold", pack: "Hộp 10 vỉ x 10 viên", retailUnit: "1 vỉ / 1 viên", barcode: "8931344969322", manufacturer: "—", sdk: "GIẢ-116", isRx: false, groupId: "otc_pain_cold", groupLabel: "GIẢM ĐAU – HẠ SỐT – HO CẢM", groupAccent: "#2563eb", bodyColor: "#eff6ff", textDark: true, boxesPerRow: 3, unitPrice: 18000 },
  { id: "kha-001", sku: "KHÁ-001", name: "Amoxicillin", brand: "Amoxicillin", generic: "Amoxicillin", strength: "500 mg", form: "Viên nang", category: "Kháng sinh", cabinetId: "rx_abx", pack: "Hộp 10 vỉ x 10 viên", retailUnit: "1 vỉ / 1 viên", barcode: "8933413730974", manufacturer: "—", sdk: "KHÁ-001", isRx: true, isAntibiotic: true, groupId: "rx_abx", groupLabel: "KHÁNG SINH (KÊ ĐƠN)", groupAccent: "#dc2626", bodyColor: "#fef2f2", textDark: true, boxesPerRow: 3, unitPrice: 30000 },
  { id: "ho-028", sku: "HO -028", name: "Tiffy", brand: "Tiffy", generic: "Tiffy", strength: " ", form: "Viên nang", category: "Ho cảm", cabinetId: "otc_pain_cold", pack: "Hộp 10 vỉ x 10 viên", retailUnit: "1 vỉ / 1 viên", barcode: "8933205963993", manufacturer: "—", sdk: "HO -028", isRx: false, groupId: "otc_pain_cold", groupLabel: "GIẢM ĐAU – HẠ SỐT – HO CẢM", groupAccent: "#2563eb", bodyColor: "#eff6ff", textDark: true, boxesPerRow: 3, unitPrice: 30000 },
  { id: "tie-062", sku: "TIÊ-062", name: "Omeprazol", brand: "Omeprazol", generic: "Omeprazol", strength: "20 mg", form: "Viên nang", category: "Tiêu hóa", cabinetId: "otc_resp_gi", pack: "Hộp 10 vỉ x 10 viên", retailUnit: "1 vỉ / 1 viên", barcode: "8933551438688", manufacturer: "—", sdk: "TIÊ-062", isRx: false, groupId: "otc_resp_gi", groupLabel: "HÔ HẤP – TIÊU HOÁ", groupAccent: "#0d9488", bodyColor: "#ecfdf5", textDark: true, boxesPerRow: 3, unitPrice: 30000 },
  { id: "tim-040", sku: "TIM-040", name: "Amlodipin", brand: "Amlodipin", generic: "Amlodipin", strength: "5 mg", form: "Viên nén", category: "Tim mạch", cabinetId: "rx_cardio_dm", pack: "Hộp 10 vỉ x 10 viên", retailUnit: "1 vỉ / 1 viên", barcode: "8939562407907", manufacturer: "—", sdk: "TIM-040", isRx: true, groupId: "rx_cardio_dm", groupLabel: "TIM MẠCH – TIỂU ĐƯỜNG (KÊ ĐƠN)", groupAccent: "#ea580c", bodyColor: "#fff7ed", textDark: true, boxesPerRow: 3, unitPrice: 18000 },
  { id: "dun-104", sku: "DÙN-104", name: "Betadine", brand: "Betadine", generic: "Betadine", strength: "10%", form: "Dung dịch", category: "Dùng ngoài", cabinetId: "front_topical", pack: "1 chai/hộp", retailUnit: "1 đơn vị", barcode: "8931843723936", manufacturer: "—", sdk: "DÙN-104", isRx: false, groupId: "front_topical", groupLabel: "DÙNG NGOÀI", groupAccent: "#7c3aed", bodyColor: "#f5f3ff", textDark: true, boxesPerRow: 3, unitPrice: 30000 },
];

/**
 * DRUGS = mặc định export = SCENE_DRUGS (subset 6 thuốc đại diện)
 * để giữ tương thích với scene 3D hiện tại.
 * POS và LabelEditor đã chuyển sang ALL_DRUGS để search được toàn bộ 180 SKU.
 */
export const DRUGS = SCENE_DRUGS;

export function getDrug(id: string): DrugSpec | undefined {
  return ALL_DRUGS.find((d) => d.id === id);
}

export function getDrugsByCabinet(cabinetId: string): DrugSpec[] {
  return ALL_DRUGS.filter((d) => d.cabinetId === cabinetId);
}

export const PHARMACY_INFO = {
  name: "NHÀ THUỐC GPP – MÔ PHỎNG ĐÀO TẠO",
  address: "Số 207, Giải Phóng, Hai Bà Trưng, Hà Nội",
  phone: "024 1234 5678",
  taxCode: "0101010101",
  gpp: "GPP-HN-2024-0001"
};

export const VAT_RATE = 0.08;
